### PR TITLE
Remove internal miner

### PR DESCRIPTION
**Pull request by deadalnix**
backport from core. Depends on #212

### CODE REVIEW

**Comment by sickpig** [comment]
WRT miner code: I think we are using it for the nol (no limit) network testing. @gandrewstone isn't it?

**Comment by ftrader** [comment]
This needs explanation:

Where is the mining code for testnets moving to?
Is there a direct relationship to https://github.com/BitcoinUnlimited/BitcoinUnlimited/pull/212 ?

**Comment by deadalnix** [comment]
What is core doing ? I think they use getblocktemplate and mine from there. Why don't we do the same ?

**Comment by ftrader** [comment]
As long as we extract the code in such a way that it remains possible to CPU-mine on a (non-regtest) testnet, I'm fine with it. But I didn't see such code from Core.

**Comment by dgenr8** [comment]
Removing the internal miner is not such a hot idea. It demonstrates a fundamental part of bitcoin and has been very useful to me anyway, in researching forks on testnet.

**Comment by ptschip** [comment]
I agree ..it's no big deal keeping the code and we never know when it
might come in handy.

**Comment by deadalnix** [comment]
You can still use the generate RPC call to mine using CPU with that patch. I don't think it makes a lot of sense to diverge from core here, and removing state from API is always a good idea.

**Comment by gandrewstone** [comment]
I would like to keep the internal miner at this point.  The PR that I'd like to merge simultaneously removes the internal miner and adds a small program that acts as an external CPU miner.  But I'm not sure if this is worth the effort.  Is there a way the dependency on this from all the other PRs backport can be removed?

**Comment by deadalnix** [comment]
The problem is that core refactored the RPC code down the road, so we'll have to redo it manually to keep the miner around. Down the road, this ties with the incompatibility with OpenSSL 1.1 . Arguably this can be do without, but it would be significantly more work. If we are to put more work into this, I'd rather make a miner using the RPC API than doing it keeping this alive.

**Pull request closed without merging**
