### PR TITLE
[Refactor] Eliminate `using namespace std` in main.cpp

### PR DESCRIPTION
**Pull request by Justaphf**
`using namespace std` is a code smell that should be eliminated.
I don't consider this terribly high priority, but as a pre-cursor to a pre-cursor I needed to convert some of the standard library items over to using `std::<name>` prior to moving them out of `main.cpp` into their own code file.  Since I needed to change a few of them, it seemed a worth-while time to convert the entire `main.cpp` file.  

To that end I:
1. Wrote a python script to update standard library types to use `std::<name>` instead of relying on `using namespace std` and added below `./contrib/devtools/`.  This script takes a file name as input and converts the file in-place.  I recommend using this on one file at a time, and inspecting the results with a fine eye to detail prior to subsequent commits.  I tried to make it smart enough to not double up for items that already have an explicit namespace, and to exclude variable/method names that just happen to match std types, comments, strings, and includes.  However, due to limitations of the built-in python regex where lookbehinds require fixed width, it is not as robust as I would like.
2. Ran the script on `main.cpp` and eliminated use of `using namespace std` in this file.
3. Verified that `make check` and standard RPC tests still pass on a Debian Jessie machine.

NOTE: The python script is still very preliminary.  It includes less than 1% of the C++ standard library keywords for conversion.  The current form is sufficient to convert `main.cpp` without requiring additional manual intervention beyond manually deleting the `using namespace std` line, but runs on other files will likely require additional updates to the python script to add new keywords to the replacement list and handle additional edge cases I haven't thought of/encountered where something that matches a std type but isn't a std type and shouldn't be converted.

### CODE REVIEW

**Comment by Justaphf** [comment]
Found a few additional standard library types that weren't in the keyword list but didn't cause compile errors after removal of `using namespace std` (`deque`, `make_pair`, `ostringstream`).  Investigating closer to see if there are more that I missed.

**Comment by Justaphf** [comment]
1. Did a survey of the code for standard library types and functions already using the `std::` prefix and added to the conversion script's list of keywords.
2. Performed a line-by-line scan of `main.cpp` and found a few additional math function calls and added to the conversion script's list of keywords.
3. Reran the script on `main.cpp` with the updated list of keywords.
4. Discovered that `using namespace std` is in the header file `parallel.h`, which was why previous build where `deque`, `make_pair`, and `ostringstream` didn't have the `std::` prefix still compiled without error.  Ran the script on `parallel.h` to remove the need for `using namespace std` there.
5. Reran `make check` and the qa tests (non-extended), all of which still passed.

~~NOTE: Running the script on `parallel.h` to remove the `using namespace std` line tripped the Travis check for formatting.  It looks like clang-format has not been run on the parallel.{h|cpp} files.  I tried running the formatting script on `parallel.h`, but it touches almost every single line so it should not be committed as part of this PR as it hides the other changes.~~

~~Leaving this as WIP until a PR for clang-format being run on parallel.{h|cpp} is merged, after which i will rebase this PR on top.~~

EDIT: Strikethrough comments about clang-format.  Issue was that I used `clang-format-3.6` while the current script requires use of `clang-format-3.8`.

**Comment by Justaphf** [comment]
It looks like the issue with clang-format was that I was using `clang-format-3.6`, not `clang-format-3.8`.  When I ran with version 3.6 the entire file was modified to a non-matching style, making the diff impossible to read.  However, when I ran with version 3.8 the only difference was an extra newline being removed where my helper script had removed the `using namespace std` line in `parallel.h`

As a side-note, in a separate PR we should probably update the supported list of clang-format versions in the `clang-format.py` script to only allow 3.8 since 3.6 clearly doesn't work as intended.

NOTE: Installing `clang-format-3.8` actually got me version 3.8.1.  The `clang-format.py` script currently only supports up to version 3.8.0, so I did have to tweak it to get it to treat 3.8.1 as supported.

EDIT: Reworded for clarification.

**Comment by maryonomemi** [comment]
whatt,confuse

Pada tanggal 17 Apr 2017 9.33 PM, "Justaphf" <notifications@github.com>
menulis:

**Comment by Justaphf** [comment]
@maryonomemi Sorry for the confusion, I edited my two previous comments to hopefully eliminate the confusion.

The main gist of the formatting issue is that Travis CI now verifies conformance to coding style standards in some files, and one of my changes tripped that check.  I attempted to remedy the issue by using the contrib/devtools script `clang-format.py` to auto-format the file, but I was running it with an old version of clang-format installed (v3.6), which mangled the file.  I realized later that the current script seems to require clang-format version 3.8.  After installing the correct version and re-running the script it turns out the style error was just an extraneous newline, which I had introduced myself when running my helper script to explicitly use `std::` and remove `using namespace std`

The whole formatting thing is a side-issue which has been resolved.  If you have questions/comments/suggestions in reviewing this PR please let me know.  Thanks!

**Pull request merged**
