### PR TITLE
Trigger August 1st UAHF by height rather than time

### PR DESCRIPTION
**Pull request by sickpig**
This simplify code a lot and more to the point a 6 months long chain reorg is not cheaply feasible.
Other than that `dev`contain also a checkpoint at the block fork height.

I'm currently testing to sync a full node from scratch to verify that this is working a part from the usua qa tests

### CODE REVIEW

**Comment by gandrewstone** [comment]
The miningForkTime tweak and related logic will be needed the next time we fork, which is scheduled for May.  If we remove these, we will just have to reconstruct all the fork-by-time logic and tests soon.  Instead, let's keep all this code, but at the same time keep all of your changes that trigger the UAHF fork based on block height.  So the miningForkTime will do nothing right now because the contents of the new fork is not defined.  But we can still verify that the fork logic works, and easily put stuff into the next fork as it is scheduled.

To make this happen without problems, let's change the miningForkTime name as used the .conf file (so not the variable name, the string name) to something like "forkMay2018".  This way, if someone has an old config file, the old setting will not apply to the new fork.

We can do procedure for every fork -- a few months after it activates, we switch the consensus logic to work by block height, create a new checkpoint, and reuse this fork time logic for the next fork.

**Comment by sickpig** [comment]
> The miningForkTime tweak and related logic will be needed the next time we fork, which is scheduled for May. 

>  let's keep all this code [time based fork code], but at the same time keep all of your changes that trigger the UAHF fork based on block height. 

the code that implemented the fork activation by time was "attached" to `CBlockIndex` class, all helpers were methods of objects instantiated from that class. i.e.

```c++
chainActive.Tip()->IsforkActiveOnNextBlock(miningForkTime.value)
```

Maintaining this and the height based code at the same time doesn't make much sense to me.

Keeping both would mean comment every `if` when the time is used rather than removing it and also keep a version of the helpers in `src/chain.cpp`, i.e. something like:

```c++
     // BUIP055 check soft-fork items, such as tx targeted to the 1MB chain
  //if (pindexPrev && pindexPrev->IsforkActiveOnNextBlock(miningForkTime.value))
    if (pindexPrev && IsUAHFforkActiveOnNextBlock(pindexPrev->nHeight))
```

Is this what you meat?

In general I wonder if an approach like we had for the deployment of the new DAA algo could be easier to implement and test, basically what we have done is: 

```c++
    if (pindexPrev->GetMedianTimePast() >=
        GetArg("-newdaaactivationtime", params.cashHardForkActivationTime)) {
        return GetNextCashWorkRequired(pindexPrev, pblock, params);
    }
```
next time we could use a tweak rather than defining an ad-hoc param.

For the new DAA we didn't re-use the fork logic we used for the UAHF/BUIP055 and I  guess we could do the same for the upcoming fork.

**Comment by gandrewstone** [comment]
I didn't mean every place in the code where an intervention is required to implement the HF.  This will change based on the HF specifics.  I meant the CBlockIndex member function definitions, the forkActivated(int time) et. al. function definitions, the CTweak, and fork_tests.cpp.

**Comment by sickpig** [comment]
@gandrewstone 

OK will do it. It would be better to do it in another PR since I have #920, #921 and #905 that depends on this one. Some of witch has been already reviewed (e.g. #920) 

Is it ok for you? 

(I will cherry-pick old commits when possible and attribute all the code to the original author).

**Comment by sickpig** [comment]
@gandrewstone see #926

**Pull request merged**
