### PR TITLE
Changed http:// to https:// on one link

### PR DESCRIPTION
**Pull request by sandakersmann**
Changed http:// to https:// on one link in README.md

### CODE REVIEW

**Comment by sickpig** [comment]
Strangely enough `wallet.py` failed, see: 
https://travis-ci.org/BitcoinUnlimited/BitcoinUnlimited/jobs/190755338#L1724

this is the actual error msg: 
```
Assertion failed: [Decimal('32.99906640'), Decimal('5650.99796160'), Decimal('66.99974900')] != [Decimal('32.99906640'), Decimal('650.99800000'), Decimal('66.99974900')]

  File "/home/travis/build/BitcoinUnlimited/BitcoinUnlimited/qa/rpc-tests/test_framework/test_framework.py", line 184, in main

    self.run_test()

  File "/home/travis/build/BitcoinUnlimited/BitcoinUnlimited/build/../qa/rpc-tests/wallet.py", line 324, in run_test

    assert_equal(balance_nodes, [self.nodes[i].getbalance() for i in range(3)])

  File "/home/travis/build/BitcoinUnlimited/BitcoinUnlimited/qa/rpc-tests/test_framework/util.py", line 608, in assert_equal

    raise AssertionError("%s != %s"%(str(thing1),str(thing2)))
```

I wonder if it is a spurious failure or something more serious

**Comment by ftrader** [comment]
@sickpig : that wallet.py failure is surely unrelated to a README change.
Someone with Travis access should restart that single failed job.

Odd: the middle number is off by the most, almost exactly 5000 coins (100 blocks?).

**Comment by sickpig** [comment]
@freetrader yeah you are right.

@gandrewstone would you mind try to restart the failed Job?

**Comment by sickpig** [comment]
@sandakersmann fwiw the webserver hosting bu.info automatically redirect (HTTP 301) all http requests to https requests.

**Pull request merged**
