### PR TITLE
Remove -minrelaytxfee as a config option

### PR DESCRIPTION
**Pull request by ptschip**
Although minrelaytxfee is used internally it is no longer a config
option and minlimitertxfee is used in its place.

### CODE REVIEW

**Comment by Justaphf** [comment]
Took a brief glance at the diff and noticed 2 points.

1. When you call `ParseMoney` you're ignoring the boolean return (what if `ParseMoney` hits a failure case).
2. When you set `::minRelayTxFee` at the end, you've lost the check for `n > 0`, intended to avoid the transaction spammer scenario warned about in the comment directly above this section.

Would suggest making that last line
```
if (ParseMoney(ss.str(), n) && n > 0)
    ::minRelayTxFee = CFeeRate(n);
```

NOTE: If the intent in dropping the `n > 0` was to relax the constraint to allow the user to explicitly specify that, yes, they really do want to relay any and all transactions, the `&& n > 0` could be dropped, but you should then change the default in your catch to the default value (`DEFAULT_MIN_RELAY_TX_FEE` I think).  This way the user can't accidentally end up in a relay everything situation by specifying the parameter with an invalid value.

**Comment by ptschip** [comment]
@Justaphf  you're right about the error handling..i'll push up something in a little while...the other case though is that we do allow for 0 values for minlimitertxfee and actually that's the default value.

**Comment by Justaphf** [comment]
@ptschip I was thinking about this change some more and from a user adoption/usability standpoint I don't think it makes sense to completely drop support for the old `-minrelaytxfee` config parameter yet.  I think we should still allow users to set this parameter, but log a warning that this is deprecated and will be removed in a future release (similar to how `rpcuser` and `rpcpassword` are marked as deprecated in preference to `rpcauth`).

> 2017-02-24 04:21:14 Config options rpcuser and rpcpassword will soon be deprecated. Locally-run instances may remove rpcuser to use cookie-based auth, or may be replaced with rpcauth. Please see share/rpcuser for rpcauth auth generation.

Implementing this way has the dual advantage that users don't suddenly lose the use of a familiar parameter to be replaced by a differently named parameter which serves the same purpose but with a units change on the expected input.  They also don't need to change any existing scripts/command line calls/config files (for this parameter) if switching to BU from another client implementation.  This keeps in line with the "BU is intended as a drop-in replacement" philosophy I've seen mentioned in the past.

I think the correct thing to do is:
1. Help message was removed, but maybe it should be listed in a deprecated section (or just have deprecated in the description) with a redirect to use the `-minlimitertxfee` parameter instead.
2. If the `-minrelaytxfee` parameter is detected, automatically log a deprecation message to the log file.
3. If both `-minrelaytxfee` and `-minlimitertxfee` are specified, then ignore `-minrelaytxfee`, log that both were specified and `-minrelaytxfee` is being ignored in preference for `-minlimitertxfee`
4. If only `-minrelaytxfee` is specified, treat it as an alias for `-minlimitertxfee`, log that it is being used to set `-minlimitertxfee` with a value of N, where N is the units converted value.

**Comment by ptschip** [comment]
@justaphf

minrelaytxfee was dropped as a user configurable paramater quite some
time ago in BU...we use minlimitertxfee and maxlimitertxfee...i only
realized the other day that we were still showing it on our list of
command line options after someone had been asking about it.

 I think though it would be good to have the warning system for "any"
non supported parameter...if you wanted to take that up as a project
that would be great but i think it's out of scope for this PR.

**Comment by Justaphf** [comment]
I read through the code on the usage of the min/maxlimitertxfee parameters, so I know that support was _effectively_ removed, as once an attempt is made to add a transaction to the mempool we recompute the value of `minRelayTxFee` from the other two parameters, overriding the user's input value.  The fact that a qa test and the code that actually accepts and parses the configuration setting both needed to be changed as part of this PR is actually a bugfix to the original implementation.

However, the fact that the original implementation also did not give deprecation notice for the removal of a previously valid configuration parameter is a bug IMO.  To me this is a UX design flaw and I think my point for user adoption/usability still stands.  Maybe it's beyond the scope of this PR, but I still think it is something that should be fixed in specific (versus the general case of dealing with unknown config options you mentioned).

Removal of a previously valid configuration parameter is a completely different animal than attempting to use a never valid parameter, and should be handled as such.  In the latter case we never understood what the user was attempting to do so ignoring (and in the future hopefully providing a useful error message) is fine.  But in the case where we "used to know" exactly what the user intended by setting this old parameter, and in this case even know exactly what the user should do to achieve the same desired effect by using the corresponding new parameters, we should be helping the user get there without forcing them to know right off the bat that there is a breaking keyword change between client implementations.

This, I think, will be important both to new users to Bitcoin and to users who convert from another client implementation.  New users are likely to see the plethora of "set up your bitcoin full node" guides out there that will reference this BU deprecated parameter, which has been around since at least v0.8.2.  These are the guides that have been around for years, there just aren't enough easily accessible BU guides out there yet and if you search for just bitcoin instead of BU you're sure to find the older guides at a higher search ranking.  For existing users who are switching clients, it's a matter of ease of conversion in terms of minimal changes required to existing scripts and bitcoin.conf files.

So to revise my previous points:
1. I now think full removal of the help message is good so as not to confuse users.
2. Still valid.
3. Still valid, though I'd suggest checking both `-minlimitertxfee` and `-limitfreerelay` and if either is specified then the value from `-minrelaytxfee` would be ignored (with appropraite log notification) because the user tried to setup the new parameters.
4. This one I see 3 options, which should have pros/cons weighed.  If of the 3 params only `-minrelaytxfee` is set
a. We set `-minlimitertxfee` to the unit converted value of `-minrelaytxfee` and `-limitfreerelay` to 0.  This option gives 100% parity with previous functionality of `-minrelaytxfee`.  My only worry here is that setting `-limitfreerelay` to 0 may or may not have an impact on XThin (not familiar with that implementation so not sure how helpful the "free" relay limit is with that protocol).
b. We set `-minlimitertxfee` to the unit converted value of `-minrelaytxfee` and `-limitfreerelay` to the default value.  This gives partial parity with the old functionality without the possible affect to XThin
c. We ignore the `-minrelaytxfee` value, as we do now, BUT we add in log messages explicitly saying we are ignoring it and telling the user they should be using `-minlimitertxfee` and `-limitfreerelay` instead.

**Comment by Justaphf** [comment]
On a side note, would the translations be broken for this string
`QT_TRANSLATE_NOOP("bitcoin-core", "Invalid amount for -minrelaytxfee=<amount>: '%s'"),`
based on this InitError string change:
`            return InitError(strprintf(_("Invalid amount for -minlimitertxfee=<amount>: '%s'"), mapArgs["-minlimitertxfee"]));`
?

**Comment by ptschip** [comment]
yes, thanks, i need to fix that...i had to change minlimtertxfee from
char to a double.

, On 25/02/2017 10:43 AM, Justaphf wrote:

**Comment by ptschip** [comment]
On 25/02/2017 10:28 AM, Justaphf wrote:
>
> I read through the code on the usage of the min/maxlimitertxfee
> parameters, so I know that support was /effectively/ removed, as once
> an attempt is made to add a transaction to the mempool we recompute
> the value of |minRelayTxFee| from the other two parameters, overriding
> the user's input value. The fact that a qa test and the code that
> actually accepts and parses the configuration setting both needed to
> be changed as part of this PR is actually a bugfix to the original
> implementation.
>
> However, the fact that the original implementation also did not give
> deprecation notice for the removal of a previously valid configuration
> parameter is a bug IMO. To me this is a UX design flaw and I think my
> point for user adoption/usability still stands. Maybe it's beyond the
> scope of this PR, but I still think it is something that should be
> fixed in specific (versus the general case of dealing with unknown
> config options you mentioned).
>
Yes, i agree but it's outside scope for this PR
>
> Removal of a previously valid configuration parameter is a completely
> different animal than attempting to use a never valid parameter, and
> should be handled as such. In the latter case we never understood what
> the user was attempting to do so ignoring (and in the future hopefully
> providing a useful error message) is fine. But in the case where we
> "used to know" exactly what the user intended by setting this old
> parameter, and in this case even know exactly what the user should do
> to achieve the same desired effect by using the corresponding new
> parameters, we should be helping the user get there without forcing
> them to know right off the bat that there is a breaking keyword change
> between client implementations.
>
well, yes and not in my view...if we tell the user the config option is
not valid they can always look it up in the release notes.  But yes, it
would be great to just tell them what's wrong, no doubt, that would be
helpful...
>
> This, I think, will be important both to new users to Bitcoin and to
> users who convert from another client implementation. New users are
> likely to see the plethora of "set up your bitcoin full node" guides
> out there that will reference this BU deprecated parameter, which has
> been around since at least v0.8.2. These are the guides that have been
> around for years, there just aren't enough easily accessible BU guides
> out there yet and if you search for just bitcoin instead of BU you're
> sure to find the older guides at a higher search ranking. For existing
> users who are switching clients, it's a matter of ease of conversion
> in terms of minimal changes required to existing scripts and
> bitcoin.conf files.
>
> So to revise my previous points:
>
>  1. I now think full removal of the help message is good so as not to
>     confuse users.
>  2. Still valid.
>  3. Still valid, though I'd suggest checking both |-minlimitertxfee|
>     and |-limitfreerelay| and if either is specified then the value
>     from |-minrelaytxfee| would be ignored (with appropraite log
>     notification) because the user tried to setup the new parameters.
>
minrelaytxfee is always ignored...it just isn't used anymore.  the user
can set it if they want but it's not honoured.  I don't think there is
anything else to do here other than the above mentioned system of
triggering messages on invalid config options which -minrelaytxfee is
one of.
>
>  1. This one I see 3 options, which should have pros/cons weighed. If
>     of the 3 params only |-minrelaytxfee| is set
>     a. We set |-minlimitertxfee| to the unit converted value of
>     |-minrelaytxfee| and |-limitfreerelay| to 0. This option gives
>     100% parity with previous functionality of |-minrelaytxfee|. My
>     only worry here is that setting |-limitfreerelay| to 0 may or may
>     not have an impact on XThin (not familiar with that implementation
>     so not sure how helpful the "free" relay limit is with that protocol).
>     b. We set |-minlimitertxfee| to the unit converted value of
>     |-minrelaytxfee| and |-limitfreerelay| to the default value. This
>     gives partial parity with the old functionality without the
>     possible affect to XThin
>     c. We ignore the |-minrelaytxfee| value, as we do now, BUT we add
>     in log messages explicitly saying we are ignoring it and telling
>     the user they should be using |-minlimitertxfee| and
>     |-limitfreerelay| instead.
>
I suppose though after all this, option c is easy enough to
implement...I could just put in an error check in the init.cpp, so that
we get a message if -minrelaytxfee is set in the options and give a
short explanation.  I guess this is a one off, but why not...it's easy
enough.

**Comment by ptschip** [comment]
actually that should be a char so nothing wrong that i can see there...hmmm

**Comment by ptschip** [comment]
oh wait, that doesn't look right....shouldn't have the single quotes
there? i think that's the problem.

**Comment by Justaphf** [comment]
@ptschip Thanks for humoring my rant on the UX.  It's come up a bit lately in the day job so spilling over into my other projects as well.  I do believe an alias/auto-conversion from the old config to the new may still be useful as a separate PR as it means we don't need to rely on the user correctly performing the unit conversion, simple as it is.  Though explicitly stating the conversion in the error message may be enough.

For the error message, two things:
1. Do we want it to completely error out and stop the startup process, or should it only be a warning in the log file?  I can see merit in both options.  Erroring out does force the user to fix it right away, though next release I suspect we'd have a lot of current BU users suddenly getting an error message on first run after upgrade (it would have happened to me).
2. Would suggest a revision to the error message wording: "Config option -minrelaytxfee is no longer supported.  To set the limit below which a transaction is considered zero fee use -minlimitertxfee instead.  Please be aware that -minlimitertxfee is specified in Satoshi/byte whereas -minrelaytxfee was specified in Satoshi/kB.  To convert multiply the original -minrelaytxfee value by 10000 when setting -minlimitertxfee."

NOTE: In the error message I used the conversion factor you coded in, but why is it 10000 and not 1000? 1 kilobyte = 1000 byte.

On the translation thing, I wasn't sure if it was an issue or not which is why I was asking.  Specifically the question was about the fact that the `QT_TRANSLATE_NOOP` macro's string used to be exactly identical to the original error message, but now the error message was changed by the word `minrelaytxfee` becoming `minlimitertxfee`.  Based on the now mismatch between the error message and the macro I was wondering if this meant a previously translatable string would no longer be translated.  I didn't think there was any issue related to the single quotes (and if the wording change I mentioned does affect translation the removal of the single quotes would probably have to be reverted).

**Comment by ptschip** [comment]
@Justaphf  before i squash these commits.  I wanted you to look at them...i reverted a few things. 

Added some of your suggestion to the error message.  

The math was actually incorrect, i should have diveded the minlimitertxfee by 100,000 and not just 10,000 as i was doing... 1sat/byte divided by 100,000 is 0.00001000 which is what we want.  

Also i had to revert back to const char for the default values because it only introduced more problems when calculating the intial  values in main.cpp.

**Comment by ptschip** [comment]
@Justaphf i also reverted back to the single quotes...not sure why it's giving you an error, it doesn't for me...when are you seeing that error message by the way?

**Comment by ptschip** [comment]
@Justaphf actually that error message is wrong also, we have to multiply by 100, 000 and -minrelaytxfee is in BTC/Kb not satoshi/kb...however ::minRelayTxFee is in satoshi/Kb so it's a little confusing. I'll make the change and push up.

**Comment by Justaphf** [comment]
@ptschip in `unlimited.cpp` you need to revert the string formatting in the help messages back since you reverted the constants back to char strings.

wrt the translation stuff, sorry for not being more clear.  I'm not running into an issue when I compile/execute, I'm not even sure if that message gets translated if it pops up during startup (haven't tested yet).  I just ran across the translation string in all of the `.ts` files while doing a search on the `-minrelaytxfee` parameter and was wondering if it _could_ be an issue (just based on code review).

I'm about to head out for a work trip so I won't have time to test it today, but I should have some availability around Tuesday, provided my internet is good.  The test case I would run would be as follows:
1. On a build without this PR, try to cause the old error message to pop-up with a non-english language setting which has a translation for this message specified (_ja is one of the ts files with a translation and would be very obvious given the characters).
2. If the message that pops up in the UI is not translated, then this is a non-issue.
3. If the message that pops up in the UI is translated, repeat step 1 with a build from this PR and see if the message is still translated.
4. If not still translated, fix.  I think the fix would be as simple as changing the macro and the `.ts` files (both source and translation).  The actual config parameter is not translated so I don't think any meaning would be lost doing a 1 for 1 replacement in all of `.ts` files.

**Comment by ptschip** [comment]
@Justaphf ok will do on the unlimited.cpp.

**Comment by ptschip** [comment]
@Justaphf ok thanks, there's no rush on this PR so whenever you get back it would be great if you could do the final testing.

**Comment by ptschip** [comment]
@Justaphf when you get a chance would you be able to do the final testing for this one...thanks.

**Comment by Justaphf** [comment]
@ptschip I should be able to look at this tomorrow evening.  Will let you know.

**Comment by Justaphf** [comment]
@ptschip I ran into some unexpected travel delays yesterday and didn't get a look at this, but I have blocked off some time tonight to finish this so hopefully done before 00:00 EST.

**Comment by ptschip** [comment]
np, life happens..

**Comment by Justaphf** [comment]
@ptschip Looks like the translations weren't working prior to this change so fixing that is outside the scope of this PR I think.

I think that technically everything here passes.  My only question, which would probably be good to get input from others on, is the dead stop if `-minrelaytxfee` is defined on the command line or in the bitcoin.confg file that I mentioned earlier:

> 1. Do we want it to completely error out and stop the startup process, or should it only be a warning in the log file? I can see merit in both options. Erroring out does force the user to fix it right away, though next release I suspect we'd have a lot of current BU users suddenly getting an error message on first run after upgrade (it would have happened to me).

Based on my own personal experience when I first started out, a lot of the guides found via googling explicitly mentioned setting that particular parameter as part of optimizing the node configuration (esp. if you were looking at guides for hobby mining configs).  So it wouldn't surprise me if many users have that setting sitting around in their config file/start on boot script.  It could be a bit jarring if user upgrades to 1.1 and suddenly a previously working config file now has a hard failure.  Would it make more sense to list that particular one as a warning instead of an error?  I did find that there is an `InitWarning` that we could use instead of `InitError`.  I'm going to make a test build with that change to see what it looks like.

**Comment by Justaphf** [comment]
I tried changing line 971 of init.cpp from `return InitError(` to `InitWarning(` and that seems like a smoother operation flow to me.  bitcoind displays the message on the console, and in the log file, but continues operation.  bitcoin-qt still popped up the message modally, requiring direct user interaction, but continues after the user hits OK.  I would prefer it if the pop-up was non-modal so-as not to block initial verification and sync, but that's outside of scope.

**Comment by ptschip** [comment]
i totally agree, i think the error was a bit jarring...i'll make the
change and push up.

thanks again for your valuable input!

**Comment by ptschip** [comment]
@Justaphf strange, using InitWarning throws up the warning but if I click ok then the UI comes up but it can't find the block source...and it neither will it begin a new sync.  It doesn't even create a log file...I"m on Windows 10, what did you test on?

**Comment by Justaphf** [comment]
@ptschip I ran into that the first time I switched to InitWarning because I left in the return statement.  If you remove the return so that the init function runs fully then it should work.

**Comment by Justaphf** [comment]
I'm on windows 10 as well.  I just had a weird issue when reapplying the InitWarning line where it didn't recompile the init intermediate object file correctly and I had to manually delete it and build again.  Somehow I got half the functionality where it displayed as a warning instead of an error, but then closed the UI after hitting OK instead of continuing, as if the return was still there.  After manually cleaning the intermediate object file and recompiling everything seems correct though.

**Comment by Justaphf** [comment]
OK, I think I figured out the previous weirdness I mentioned, seems that I hadn't saved the last changes in init.cpp and when I closed out VS during my mingw build it auto-saved the changes mid-compile.  Everything has been fine on subsequent builds.

**Comment by ptschip** [comment]
@Justaphf thanks again, the "return" was the problem...pushed up the final changes.  Waiting for your approval..

**Comment by Justaphf** [comment]
Did a quick test on Debian as well.  Everything looks good for merge now.

**Review by Justaphf — APPROVED** [review]

**Comment by sickpig** [comment]
@gandrewstone according to @Justaphf and @ptschip this PR is ready to be merged. Is there any reasons why we haven't merge it yet?

**Pull request merged**
