### PR TITLE
Use CASH net magic by default when establishing outgoing conns

### PR DESCRIPTION
**Pull request by sickpig**
title is self explanatory, to apply ***after*** the next release

### CODE REVIEW

**Comment by sickpig** [comment]
rebased

**Comment by sickpig** [comment]
taking out of WIP since BUCash 1.1.2.0 is out of the door

**Comment by ptschip** [comment]
@sickpig shouldn't we also take out the fUsesCashMagic logic that is in ProcessMessages() in main.cpp?  we don't (isn't it now not necessary).

**Comment by sickpig** [comment]
IMHO it is better to do it in another PR.

Currently we use  `fUsesCashMagic` in "mixed" ways.  In `net.cpp` we set it up using `#ifdef BITCOIN_CASH` directive, whereas in `net.h` we use it "plain". In `main.cpp` we use in both ways.

That said I agree that we should remove it, but to do so we need a PR for `dev` and one for `BitcoinCash`, cause at that point the magic will be a point of differentiation.

**Comment by ptschip** [comment]
@sickpig ok, perhaps a step wise approach is safer...

**Review by ptschip — APPROVED** [review]

**Pull request merged**
