### PR TITLE
fix for issue #314  Invalid Message Start

### PR DESCRIPTION
**Pull request by ptschip**

### CODE REVIEW

**Comment by ptschip** [comment]
@gandrewstone this PR should get backported to the Release branch when it's accepted...

**Comment by ftrader** [comment]
@ptschip : why do we need to apply the banhammer on such a node - what is actually causing the subsequent crash?

**Comment by ptschip** [comment]
@ftrader i beleive the problem is actually being caused by not disconnecting the
node safely using the fDisconnect flag.    I also think we should still
ban these nodes in the code anyway..if someone is feeding us an invalid
message start we don't want to give them a chance to do it repeatedly.

**Comment by ptschip** [comment]
@ftrader line 2037 on net.cpp i think is the real culprit...I've been running a test with pnode->fDisconnect = true...and not banning the node and so far it's still running but it's only been 5 or 6 hours.  

            // Receive messages
            {
                TRY_LOCK(pnode->cs_vRecvMsg, lockRecv);
                if (lockRecv) {
                    if (!g_signals.ProcessMessages(pnode))
                        pnode->CloseSocketDisconnect();

**Comment by ftrader** [comment]
>if someone is feeding us an invalid message start we don't want to give them a chance to do it repeatedly.

I would agree with that.

**Comment by ptschip** [comment]
i would like to but there is no way to do that...it's all or nothing at
this point in the code...the problem is that we need to lock cs_main if
we want to DOS (20) for example..but that will/may cause a deadlock
here.  So we can only ban 24 hours here.   I don't see an issue really,
this message is not something that is seen often if ever...but yes, it
would be good to be able to give them a few tries but really that needs
a lot of refactors but it is something that is on my list, that is, 
removing the need for cs_main in several places in the code.

**Comment by ptschip** [comment]
@ftrader what about banning for a shorter duration, maybe just 4 hours, like we do in the connection slot algorithm?

**Comment by ptschip** [comment]
@ftrader @sickpig  I was able to reproduce the issue by just disconnecting every once in a while when a message would come in.  So it's not the Invalid Messagestart that is the cause but as i suggested, it's the disconnect on returning "false" from ProcessMessages()

I'm going to run another test , this time with the pnode->fDisconnect's in place but without banning.

**Comment by ptschip** [comment]
and here is i believe the root of the problem....in the threadsockethandler, pnode->vRecvMsg is not locked.  vNodes is locked however that does not lock vRecvMsg.  vRecvMsg gets cleared when the socket is disconnected outside the threadmessagehandler (whic is why we need to use the fDisconnect flag) but then we try to access it here at the same time...hence the problem .  And we would never have seen because the only way to trigger it is in one place...return false from Invalid Message Start...

around line 1250 net.cpp:

                if (pnode->fDisconnect ||
                    (pnode->GetRefCount() <= 0 && pnode->vRecvMsg.empty() && pnode->nSendSize == 0 && pnode->ssSend.empty())) {
                    // remove from vNodes
                    vNodes.erase(remove(vNodes.begin(), vNodes.end(), pnode), vNodes.end());

**Comment by ptschip** [comment]
regardless i think we'll have to lock vRecvMsg here anyway, because it can and is accessed elsewhere from processmessage() in main.cpp.

**Comment by ptschip** [comment]
oh boy, well we can't lock vRecvMsg after vNodes because of the locking order..hmmm...i guess i see why they did the fDisconnect flag, but still there's potential for a further problem down the road IMO.

**Comment by ptschip** [comment]
@gandrewstone  this line is a problem because we can't lock vRecvMsg without the potential for a deadlock.  I'm wondering whether we really need this at all?  I mean , if the ref count is <=0 isn't that enough for us to initiate a disconnect?  do we really need to check vRecvMsg!!!

                    (pnode->GetRefCount() <= 0 && pnode->vRecvMsg.empty() && pnode->nSendSize == 0 && pnode->ssSend.empty())) {

**Comment by ptschip** [comment]
actually pnode->vRecvMsg.empty() should be thread safe...so i think we're good on that...i think it's down to the disconnects called from different threads that is really the problem...

**Pull request merged**
