### PR TITLE
[WIP] Stagger the rotation start times in ThreadMessageHandler()

### PR DESCRIPTION
**Pull request by ptschip**
If we don't do this then all the threads will end up rotating one
after the other at each rotation interval. This ends up rotating all
nodes by the number of message handler threads at each interval. By
staggering their start times we end up getting one thread doing a rotation
at each interval.

The 60 second interval is now multiplied by the number of handler threads so
this way we get a smooth 1 minute between rotations, since we stagger the
start times for each thread also by 60 seconds.

### CODE REVIEW

**Review by sickpig — APPROVED** [review]

**Comment by gandrewstone** [comment]
The rotation code is locked by cs_vNodes so only 1 thread can run it at at time.  The way I read it, that code updates nLastRotation, so once it runs the logic won't trigger in any other threads for another nRotationPeriod seconds.

**Comment by ptschip** [comment]
Problem is every thread is basically starting at the same time when they
are initialized.  That's what I'm trying to stagger...the very first
nLastRotation time that is assigned.  So what I'm doing here is taking
the atomic value of nThisThread which will for four threads be either 0
or 1 or 2 or 3 and then subtracting 60 seconds * nThisThread.  This way
each thread will rotate 60 seconds apart from one another.  Whereas, the
way it is in the code right now they do 4 rotations suddenly at every 60
second interval.

**Comment by dgenr8** [comment]
So you are not only staggering the rotations, but also reducing the overall average frequency of rotation.

**Comment by ptschip** [comment]
the overall frequency is the same, 60 seconds between rotations...if you
have one thread the frequency is 60 seconds...2 threads and it's 120
seconds, but that means every 60 seconds you get a rotation....for 4
threads it's 240 seconds before a thread rotates, so that's once every
60 seconds overall, since they're equally spaced. etc...

**Comment by dgenr8** [comment]
Ok, I missed that rotate is an operation done on the vector of nodes, not to each element. Best to understand everything that's going on before commenting :face_with_head_bandage:

**Comment by gandrewstone** [comment]
I don't read the original code as doing 4 rotations suddenly after 60 seconds.  What I'm reading is that 1 thread gains the lock and does 1 rotation, updating nLastRotation (it is defined static so there's just 1 of them).  The rest don't rotate because when they gain the lock nLastRotation has already been updated.

**Comment by ptschip** [comment]
yes you're right, i didn't consider it at the time, it makes perfect
sense, but when i tested it i could have sworn that it  rotated 4 at a
time...hmmm, maybe i'm seeing things...i'll go back and test it again.

**Comment by ptschip** [comment]
@gandrewstone tested again...you're right it doesn't make any difference. Not sure what I was seeing that led me down this path...time for a vacation I think... 

Closing...

**Pull request closed without merging**
