### PR TITLE
test: move accounting_tests and rpc_wallet_tests to wallet/test

### PR DESCRIPTION
**Pull request by deadalnix**
Backport from core. Depends on #215

### CODE REVIEW

**Comment by ftrader** [comment]
curious: why are so many commits here being tested individually by Travis?

**Comment by deadalnix** [comment]
Because GitHub is completely broken and doesn't support stacked diff. As a result, one is left to either do a kitchen sink PR, or do stacked PR and get GitHub to crap itself.

**Comment by ftrader** [comment]
Thanks for the explanation.

**Comment by gandrewstone** [comment]
merged via PR 313

**Pull request closed without merging**
