### PR TITLE
[qa] Test for electrum cashaccount support

### PR DESCRIPTION
**Pull request by dagurval**
Marked as WIP because https://github.com/dagurval/electrs/pull/1 needs to be merged first

### CODE REVIEW

**Comment by sickpig** [comment]
@dagurval need a rebase.

**Comment by dagurval** [comment]
I'll rebase after https://github.com/BitcoinUnlimited/ElectrsCash/pull/2 is merged

**Comment by dagurval** [comment]
Rebased and out of WIP state

**Comment by sickpig** [comment]
@dagurval if you rebase again you'll get rid of the travis failure that is due to a centos new release.

**Review by sickpig — APPROVED** [review]

**Pull request merged**
