### PR TITLE
reformat all files in src wallet test rpc and qt

### PR DESCRIPTION
**Pull request by BitcoinUnlimitedJanitor**

### CODE REVIEW

**Comment by sickpig** [comment]
for some reasons related to formatting travis is failing on linux 64bit stanza:

https://travis-ci.org/BitcoinUnlimited/BitcoinUnlimited/jobs/272232391#L761

not clear what was actually failing thou.

**Comment by ptschip** [comment]
looks good but one file i think was missed  qt/paymentrequest.pb.h  ?  i think that's why travis failed..the file was included in the list of formatted files but never was formatted?

**Comment by BitcoinUnlimitedJanitor** [comment]
thanks.  File is autogenerated so should not be part of the format checking.

**Comment by ptschip** [comment]
@gandrewstone needs a rebase

**Comment by sickpig** [comment]
@gandrewstone this one needs a rebase

**Comment by gandrewstone** [comment]
issued a different PR

**Pull request closed without merging**
