### PR TITLE
Fix png files to prevent libpng warnings

### LINKED ISSUE #240: libpng errors on start
I'm getting two libpng errors when launching qt from command line.

libpng warning : iccp: known incorrect sRGB profile
" " cHRM chunk does not match sRGB

### PR DESCRIPTION
**Pull request by kyuupichan**
Fixes #240 

I figured out how to detect the broken PNG files and only fixed those.  It seems to have been the new BU images.

### CODE REVIEW

**Comment by kyuupichan** [comment]
Here are the warnings on starting the Qt GUI from the command line that this PR fixes.  They print to the console (not the logs):

libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB

**Review by sickpig — APPROVED** [review]

**Comment by sickpig** [comment]
@kyuupichan how did you manage to detect the broken PNG?

**Comment by kyuupichan** [comment]
@sickpig google was my friend :)  There's an app apparently bundled on OSX
called pngfix that tells you if the given png would issue a warning or
error by libpng.  It has other features as well but I didn't use them.  I
used ImageMagick's mogrify to fix the png files that pngfix reported.

**Comment by gandrewstone** [comment]
thanks for adding details!

**Pull request merged**
