### PR TITLE
socks5 QA tests: Make "Address already in use" errors less likely

### PR DESCRIPTION
**Pull request by awemany**
This will loop through a couple of subsequent (with quadratically
increasing gap) addresses if binding a socket fails to an address.

This should make errors like this one

https://travis-ci.org/BitcoinUnlimited/BitcoinUnlimited/jobs/315036165

much less likely.

To test this commit, do

"nc -l -p 13000" and maybe "nc -l -p 13001" on another console to bind
and block tcp:13000 on your computer, temporarily change proxy_test.py
so that one of its socket config lines read:

        self.conf1.addr = ('127.0.0.1', 13000) #+ (os.getpid() % 1000))

instead of

        self.conf1.addr = ('127.0.0.1', 13000 + (os.getpid() % 1000))

And then start proxy_test.py from the bitcoin base directory. It should
tell you that it tried opening sockets and failed and advanced to the
next one.

### CODE REVIEW

**Comment by awemany** [comment]
Damnit and this now fails on another - as it looks like - spurious issue. Can someone tell me what is going on here, and why test_bitcoin says 'failure'? I have a deja vu with this one as well.

**Comment by sickpig** [comment]
PR test fails on `proxy_test.py`

kicking travis job to see if it is a reproducible error.

**Comment by awemany** [comment]
@sickpig: It does, *here*? Where do you see that in the log?

I find:
``` proxy_test.py                  | True   | 3 s```

for this one.

**Comment by sickpig** [comment]
job `#2656.5` was failing 
unfortunately I restarted it so we lost the log of the first run. now it seems to have passed, but we still have a failure on #2656.1: https://travis-ci.org/BitcoinUnlimited/BitcoinUnlimited/jobs/315349624#L962

```
FAIL: test/test_bitcoin

=======================


Running 242 test cases...

../../src/test/coins_tests.cpp(278): error: in "coins_tests/coins_cache_simulation_test": check reached_4_caches has failed

2017-12-12 13:12:59 ../../src/test/util_tests.cpp(60): Debug Assertion failed: "0"


*** 1 failure is detected in the test module "Bitcoin Test Suite"
```

are you able to reproduce it locally (via `make check`)?

**Comment by awemany** [comment]
```make check``` runs fine for me on this one.

**Comment by sickpig** [comment]
travis tests turned green after rekick

**Review by sickpig — APPROVED** [review]

**Comment by ptschip** [comment]
@awemany the failures in the coin_cache tests is one due to just an unlucky random number selection.  It's caused by the recent reduction in number of iterations from 40000 to 10000 of that particular test.  I wonder if we went a little too far..we'll see if we get more of these failures in the future but at any rate it has nothing to do with your PR.

**Review by ptschip — APPROVED** [review]

**Comment by gandrewstone** [comment]
Thanks!  The sporadic qa test failures are a thorn in our side.  It is great to address them!

**Pull request merged**
