### PR TITLE
[WIP] set -relaypriority to false

### PR DESCRIPTION
**Pull request by ptschip**
Solution for issue #77 and removes yet another magic number which is already covered by -limitfreerelay.

### CODE REVIEW

**Comment by ptschip** [comment]
Rather than take the functionality out entirely I thought we should just set the default to false for now in case there is anyone out there that uses the feature for some reason.

**Comment by ftrader** [comment]
If the intention going forward is to deprecate `-relaypriority`, then there should maybe be a few things more:

- add a note at the definition to mark it as TO BE DEPRECATED or similar
- in the cmdline help for this parameter, add a blurb like `(deprecated)`
- mention it clearly as a deprecated option in the next Release Notes

That should increase the chances that current users of the option might get wind of its retirement.

**Comment by ptschip** [comment]
On 02/02/2017 1:17 PM, freetrader wrote:
>
> If the intention going forward is to deprecate |-relaypriority|, then
> there should maybe be a few things more:
>
>   * add a note at the definition to mark it as TO BE DEPRECATED or similar
>
i'll add a note
>
>   * in the cmdline help for this parameter, add a blurb like
>     |(deprecated)|
>
|there is no cmdline help...this option was not even showing in the list
of availble options. I"m not even sure why it was here...I believe this
was probably the beginning of core in exerting fee market pressure (this
feature arrived in v10.x) but I really don't know.|

**Comment by ftrader** [comment]
> I"m not even sure why it was here

This seems part of a larger problem of undocumented options. I'll raise a ticket to document those.

**Comment by gandrewstone** [comment]
Its one thing to deprecate a flag and leave it as the default behavior, but this PR seems to deprecate the flag and reverse the default behavior.  So we need to be careful.  My concern here is that someone might make a transaction with too low a fee to be mined, and this code catches that.  But perhaps that is already better handled by the fee picker in the transaction construction code?

And the code seems to handle limiting free transactions in a much more elegant manner in the code block starting on line 1420.

        if (fLimitFree && nFees < ::minRelayTxFee.GetFee(nSize)) ...

So just to be clear, I am cautiously ok with merging this change...

But I noticed one issue: sorry to hijaak this thread but in the code on line 1420 we test against nFees.  I am thinking we should test against nModifiedFees.  By using this variable, we won't reject the transaction if a miner elevates the priority using the prioritisetransaction CLI call.

**Comment by ptschip** [comment]
@gandrewstone   it's funny we've been discussing this while at the same time Core is going to completely remove this functionality  although for a different reason...They want to force everyone to pay a fee while we want to allow just the opposite.  My original aim was to remove this and not just disable it, so in the light of core removing it I think we should do the same.  

Here is the commit that they are working on.
https://github.com/bitcoin/bitcoin/pull/9602/commits/d0c30f170eb6bd99bbdf492f54fa01b2db16eb76

thoughs?

**Comment by ptschip** [comment]
Changing to WIP until we can figure out whether we should just disable this or take it out completely as Core is planning to do.

**Comment by ptschip** [comment]
closing for now, it doesn't seem we're getting any resolution on this one yet.

**Pull request closed without merging**
