### PR TITLE
Fix Trailing Comments - Group 1

### PR DESCRIPTION
**Pull request by marcusdiaz**
What I did for this PR was to start with all the files located in the projects
/src directory ending in .cpp or .h. Then, I split that universe into
three parts to correspond with three PR's.

Among each group, I also excluded any files which I found to have been modified
in PR#412.

Among the remaining source files, I processed each file through a script which
would find cases of:

    "something here; //then a comment"

and modify that to:
    //then a comment"
    "something here

I reviewed a diff between the modified source file and it's original
version looking for any anomolies.

Finally, I compiled the project and ran both bitcoind -daemon and tested
a few ad-hoc commands via the bitcoin-cli.

### CODE REVIEW

**Comment by ftrader** [comment]
For some reason I'm really nostalgic about leaving the trailing header file name on closing `#endif` directives.

I don't see sense in separating those. One of those few times where I feel consistency could do with an exception.

**Comment by gandrewstone** [comment]
Marcus, I think that we decided to move the trailing comments up if the total line exceed 120 characters but not to remove them entirely.  The "janitor" has checked in a script that accomplished that in a recent commit.  We are going to apply it and clang-format to source files as they are touched by the project.
  
Also, from an attribution perspective, its not really fair to give a person attribution to so many secretarial changes, so I created a "BitcoinUnlimitedJanitor" account to make these kinds of changes.

I am sorry that we duplicated effort on this! :-(

**Comment by sickpig** [comment]
@gandrewstone I thought we decided to move all trailing comments up independently from line length. If memory serves the only objection has been done by @ftrader about trailing comment on `#endif` directive. Am missing something?

**Comment by gandrewstone** [comment]
hmm... I thought we decided only up to the line length, its a big waste of space if you can't use those 120 columns to describe what you are doing :-)
EDIT: I quickly searched the slack for "trailing comment" and skimmed the conversation from the top.  It seems it was not discussed.  For things that were not discussed I left them as they were defined in Core's .clang-format.

**Pull request closed without merging**
