### PR TITLE
fix UI issues - cltv balances, send public labels, fix private label display and tx search for all addresses

### PR DESCRIPTION
**Pull request by marlengit**
This PR was made to apply after #266 (coin_freeze_cltv). Re cltv it fixes the bug where private label is not showing so all labeled freeze txs are easier to find. 

This PR fixes these UI issues :
1. Fix private label to display in the Transaction tab for **all** txs.  
2. Fix the Transaction tab list which failed to include **all** addresses (inputs/outputs) of a transaction.  So no more "(n/a)" values in the list instead all addresses/private labels are displayed. Now the standard search feature will find all your old txs via addresses/private labels filter. Previously the search feature often failed to return txs related to the address/label which the user types into the filter. (Note: public labels cannot be searched in the filter still only private labels are in this fix).
3. On the Send tab expose the OP_RETURN "public msg" feature. This integrates with the Transaction tab display where public labels stored in the blockchain are displayed between <> quotes. It implements a display standard that an OP_RETURN _preceding_ an UTXO is assumed to be its public label in the Transaction list.
4. Fix Overview Balances Watch Only which doesn't include cltv amounts sometimes.
5. Fix 'Transaction details' dialog not showing some addresses. Also append freeze label to description.

### CODE REVIEW

**Comment by marlengit** [comment]
I might have messed up merging in 0.12.1bu instead of dev .....I'm a bit confused about the state of the upstream branches atm.

**Comment by sickpig** [comment]
the current branch where we are going to add new features is the `dev` branch. 

fwiw the travis failure seems "real" to me, this the actula error mesg: 
```
  CXX      test/test_test_bitcoin-multisig_tests.o
  CXX      test/test_test_bitcoin-netbase_tests.o
../../src/test/multisig_tests.cpp: In member function ‘void multisig_tests::opreturn_send::test_method()’:
../../src/test/multisig_tests.cpp:399:30: error: ‘getLabelPublic’ was not declared in this scope
     outMsg = getLabelPublic(s);
                              ^
make[2]: *** [test/test_test_bitcoin-multisig_tests.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/home/travis/build/BitcoinUnlimited/BitcoinUnlimited/build/src'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/home/travis/build/BitcoinUnlimited/BitcoinUnlimited/build/src'
make: *** [install-recursive] Error 1
Build failure. Verbose build follows.
Making install in src
```

**Comment by sickpig** [comment]
After the last rebase trvis is failing in the x86_64 (stanza #7) where among other settings there's one (NO_WALLET=1) that disabled the build of wallet dependencies (e.g  berekeley db).

What it seems to happen is that the c++ test for the wallet is built even if the wallet functionality is disabled and this means that berkeley development package is not installed, hence no headers...

Did you change/add something in the c++ libboost test suite?

**Comment by gandrewstone** [comment]
I've merged the "dev" branch out to coin_freeze_cltv in the hopes that this would solve the issues with so many spurious files needing to be updated.  But it doesn't look like it will happen automatically.  I'm not sure what to do.  Perhaps you could close this PR, update your branch and then reopen it?

**Comment by marlengit** [comment]
It worked! I just had to pull & push coin_freeze_cltv.

**Comment by marlengit** [comment]
I've added a fix for the balance. The problem was that fHaveWatchonly was returning true only if the user had previously manually added a watch address. Now the fHaveWatchonly is also set to true whenever the watch balance > 0. So now the Watch Only column balances correctly display when there are frozen cltv amounts.

**Comment by marlengit** [comment]
Any ideas....still got 1 travis config failing? Perhaps suggesting more #ifdef ENABLE_WALLET blocks required somewhere. 

> CXXLD    test/test_bitcoin
> In file included from ../../src/wallet/walletdb.h:11:0,
>                  from ../../src/wallet/wallet.h:18,
>                  from ./../../src/qt/transactionrecord.h:11,
>                  from ./../../src/qt/transactiontablemodel.h:10,
>                  from qt/moc_transactiontablemodel.cpp:8:
> ../../src/wallet/db.h:22:20: fatal error: db_cxx.h: No such file or directory

**Comment by gandrewstone** [comment]
I've restarted just to be sure, but in this build the wallet is "off" so I think you are correct, we need a #ifdef ENABLE_WALLET somewhere to stop db_cxx.h from being included because only the wallet uses berkeley db...

**Comment by gandrewstone** [comment]
I'm going to merge this onto our working branch since the branch is isolated, and then fix the NO WALLET compilation issue here...

**Pull request merged**
