### PR TITLE
fix logo colors for ico and icns

### PR DESCRIPTION
**Pull request by Greg-Griffith**
this only fixes the color on the current logo.

marked this as WIP because of the discussions in slack about the new updated logos, unsure if this is needed. Also would like to make sure someone else built with success. im never confident with image formatting.

### CODE REVIEW

**Review by ptschip — APPROVED** [review]
compiled and tested...

**Comment by Greg-Griffith** [comment]
removed WIP since ptschip has also confirmed.

**Comment by gandrewstone** [comment]
How did you fix this?  I'd like to do the same for the new icon

**Comment by Greg-Griffith** [comment]
@gandrewstone illustrator and a icon conversion tool. i didnt do it. i know a graphics guy who did it for me

**Comment by gandrewstone** [comment]
I submitted #940 with new icons, and it solves the gray issue, so I am closing this PR.  But thanks for looking into the problem!

**Pull request closed without merging**
