### PR TITLE
Create rpc call for  getorphanpoolinfo

### PR DESCRIPTION
**Pull request by ptschip**
return the size in bytes and number of orphans

### CODE REVIEW

**Comment by gandrewstone** [comment]
@ptschip formatting...

**Comment by gandrewstone** [comment]
Please a throw a call to this new RPC into one the the python QA tests (just exercise it, don't worry about verifying correct values unless that is easy).

**Comment by ptschip** [comment]
just did

**Comment by ptschip** [comment]
done

01/08/2018 11:47 AM, Andrew Stone wrote:

**Review by awemany — APPROVED** [review]

**Review by awemany — APPROVED** [review]

**Comment by awemany** [comment]
Looks good to me. Didn't compile nor test, though.

**Review by sickpig — APPROVED** [review]
At the end you beat me to it :smile:

**Pull request merged**
