### PR TITLE
Update minimum required Qt version

### PR DESCRIPTION
**Pull request by Greg-Griffith**
change minimum required Qt version to 5.0 due to #1143 and #1011

### CODE REVIEW

**Comment by ptschip** [comment]
@Greg-Griffith I believe we are QT 5.3 minimum because of some QT date widget used in the freeze coins dialog... @sickpig can you confirm?

**Comment by sickpig** [comment]
@ptschip need to check what is the requirement here

**Comment by sickpig** [comment]
just checked. the issue that report the problem was #876. 
the problem was related to the fact that `qt/receivefreezedialog.cpp` is using `Qt::ImhDate|Qt::ImhTime` object and those are available only since `Qt 5.1`

Wonder if we could use something else in case we detect a Qt with ver 5.0

**Comment by gandrewstone** [comment]
From my reading the comments here, we need this PR bumped to a minimum of Qt 5.1 before merging...

**Review by sickpig — APPROVED** [review]

**Pull request merged**
