### PR TITLE
Handle non continuous headers

### PR DESCRIPTION
**Pull request by ptschip**

### CODE REVIEW

**Comment by kyuupichan** [comment]
This seems awfully complex.  Why not just send a GETHEADERS request in 2 or 3 lines of code?

**Comment by ptschip** [comment]
@kyuupichan you might be right...it started off small and started growing...it works better IMO than the  GETHEADERS method in terms of performance, and this does solve another attack vector for IBD where we can disconnect a peer that's feeding us out of order headers to prevent us from syncing.  Furthermore, the getheaders method has it's own issues, it's not just 2 or 3 lines of code, You also have to worry about getting caught in an infinite loop of re-requests; I don't thinks it's really all that clean of an approach, but you are right there would be less code.

**Comment by kyuupichan** [comment]
https://github.com/bitcoin/bitcoin/blob/master/src/net_processing.cpp#L1979-L1984

Is the code from core.  I don't see why we need anything more complex.  I don't understand your point about loops.

**Comment by ptschip** [comment]
rebased

**Pull request merged**
