### PR TITLE
Move expedited.{cpp,h} to thinblock.{cpp,h}

### PR DESCRIPTION
**Pull request by kyuupichan**
This moves the expedited thinblock code to thinblock.cpp.  Along with the code moves from main.cpp this consolidates thinblock logic in one place.

This will enable reduction of header file pollution and simplify code/logic sharing and consolidation in future changes.

### CODE REVIEW

**Comment by ptschip** [comment]
@kyuupichan after thinking about it again I'm wondering if this really is a good idea afterall.  I'm not sure what we're getting out of merging these two.  Expedited, as we know uses thinblocks but there is much more to it and having the expedited code all in one place was a way of keeping what I thought would be a logical separation.  Unless there is a good rational, I would be more inclined to think that Expedited.cpp would go in a more general netprocessing.cpp similar to what Core has done?

**Comment by kyuupichan** [comment]
Well we would then also be moving most of the thinblock.cpp code to netprocessing.  I would like to keep all the thinblock code in one place.

**Comment by ptschip** [comment]
@kyuupichan I guess we have to agree to disagree on this one.   I don't see expedited as having anything necessarily to do with thinblocks....currently yes it uses thinblocks but couldn't it use any kind of block, full, compact or something else in the future? So I think keeping a logical separation between the two makes some sense.

**Comment by kyuupichan** [comment]
Closing for now; time should show if worth re-opening.

**Pull request closed without merging**
