### PR TITLE
bitcoin-miner: Made CPU miner thread safe by using per-thread randgen

### PR DESCRIPTION
**Pull request by cculianu**
This PR affects the toy program `bitcoin-miner` which I have been using lately 
to mine testnet, since it appears testnet stalled because all the ASIC miners
disappeared.

I noticed I was occasionally finding duplicate pow solutions (blocks) across mining 
threads (!!).  Bitcoind would return an error to one of the threads that the block is
a dupe (and console output showed both blocks had the same hash as well).  This concerned me so I investigated the code and realized the reason:
`std::rand()` was being called across mining threads but it is not re-entrant nor
thread-safe (it uses global state).

It turns out since `std::rand` was being called by multiple threads, there was a good
chance each thread was doing the same exact work as its sibling threads, thus
wasting CPU resources and making CPU mining less likely to find solutions.

So..Hence this PR.

**Performance notes:** This new lambda `randFunc` is only called a few hundred times
per tens of millions of hashing tries. It's very fast anyway -- but there should be
0 performance impact of using this method to generate the base nonce (as compared
to the previous `std::rand`, unsafe method).

Below is the commit log:

---

Previously all threads called std::rand which is not guaranteed to be
thread-safe.  In my testing by CPU mining on testnet, I would sometimes
get multiple threads finding the *exact* same block solution! This is
because std::rand() when called across threads may return the exact same
value if re-entered before it finishes updating its internal (shared)
state.

Instead, we use a lambda that leverages the C++11 std::random_device and
other functions to keep a per-thread random number generator state.

The net result is now the threads won't do redundant proof-of-work and
each thread hopefully works on its own unique set of nonces.

### CODE REVIEW

**Review by dagurval — APPROVED** [review]
utACK

**Comment by cculianu** [comment]
Just to beat a dead horse: `std::rand` returns a value between `0` and `RAND_MAX` -- on many implementations `RAND_MAX` is `0x7fffffff`, and on some, it's as low as `0x7fff`.  

So definitely we don't want to use `std::rand` here. :) 👍

**Review by sickpig — APPROVED** [review]

**Comment by gandrewstone** [comment]
nice catch!  Thanks

**Comment by cculianu** [comment]
Scratched a personal itch.. :)

**Pull request merged**
