### PR TITLE
DRY refactor on dbwrapper CDBWrapper::Read

### PR DESCRIPTION
**Pull request by gubatron**
Found repeated code in dbwrapper's `CDBWrapper::Read` that should be using the logic inside `CDBWrapper::Exists`

I tried to make

`bool Exists(const K &key, std::string &strValue) ` have its second parameter with a default value, but that would've meant using a `const std::string &strValue=""` parameter which would've triggered what I think had been a cascade of parameter refactors starting with `Status::Get`. Therefore the solution with 2 `Exists` methods.

### CODE REVIEW

**Review by ptschip — APPROVED** [review]

**Review by sickpig — APPROVED** [review]
nice catch @gubatron

**Comment by gubatron** [comment]
Thanks. Got a bunch of these coming, I'm using a tool to find repeated code and will try to accomodate as much as possible. This will serve me to get familiar with the codebase and then be a bit more productive.

**Comment by sickpig** [comment]
@gubatron Good to know! Many thanks for your effort. Which kind of tool are typically using?

**Comment by gubatron** [comment]
To find repeated code I'm using PMD's `cpd` tool.

https://pmd.github.io/
https://github.com/pmd/pmd

I made an easy to use alias command
```
# CPD - Copy/Paste Detector (Code Analyzer)
# Example:
# cpd --minimum-tokens 100 --files . --language cpp
alias cpd="/Users/gubatron/workspace/pmd/pmd-dist/target/pmd-bin-6.3.0-SNAPSHOT/bin/run.sh cpd"
```

As for development, I'm working on CLion. To properly work on it I'm working on a `CMakeLists.txt` file so the IDE can help me navigate and refactor the code with ease, perhaps somebody else out there coming from Java-land as myself will appreciate being in an environment as powerful as IntelliJ for C++. I'll share this `CMakeLists.txt` if you guys find it of use for other developers, it's meant to be a coding makefile, not meant to replace the current building infrastructure.

**Comment by awemany** [comment]
@gubatron: Help is always appreciated, thank you!

On this:
> I'll share this CMakeLists.txt if you guys find it of use for other developers, it's meant to be a coding makefile, not meant to replace the current building infrastructure.

My opinion is that this should be either:

a) auto-generated from the Makefile.am, if possible
b) backed by someone willing to keep it up-to-date to Makefile.am

Because I think it is all too easy for it to get out date and be more pain (at least of false expectations) than it is worth.

**Comment by gandrewstone** [comment]
@gubatron: I love to see these kinds of code cleanups!  Can I beg you to go all the way and add documentation for all the functions you've touched (and especially the function you added): Describe what it does, what parameters it takes, what it returns (both ret value and return parameters), what it throws, and how it errors.  If you poke thru the code you can find API documentation examples, but unfortunately of inconsistent thoroughness -- basically its doxygen format but is not consistently applied.

**Comment by gubatron** [comment]
got it, will do on the next one.

**Pull request merged**
