### PR TITLE
[WIP] - Fix QA tests when Graphene is on by default

### PR DESCRIPTION
**Pull request by Justaphf**
Looks like fixing QA tests was as simple as explicitly turning off Graphene in the same places that we explicitly turn off XThin, with the addition of also explicitly turning it off for the XThin specific tests.

NOTE: This also turns Graphene back on by default.

### CODE REVIEW

**Comment by Justaphf** [comment]
I'm leaving this as WIP until Travis passes.  All tests for no parameter and `--coverage` passed on my Ubuntu machine.

**Comment by ptschip** [comment]
while these changes are probably ok, i don't think some of the other
tests will pass, there is actually a bug in requestManager.cpp
(requestblock()) which affects mainly the tests but could happen on
mainnet.  I have a fix for that but it's more involved than
expected...will work on that next week...your PR here could be submitted
against mine when I get it up and I'll merge it in...but there's no rush.

**Comment by Justaphf** [comment]
Looks like Travis is killing the tests due to the logs being too long.  I'm not seeing this on my test machine, though I just tested `--extended` which has issues (iirc there are still some outstanding issues with that switch w/o this change anyway).  Trying to rerun the tests to see if the logs get too long again, but I'll probably just close this PR.

**Comment by Justaphf** [comment]
Closing till other QA test fixes ptschip mentioned are in.

**Pull request closed without merging**
