### PR TITLE
Add BitcoinCash hardfork activation for Nov13

### PR DESCRIPTION
**Pull request by ptschip**

### CODE REVIEW

**Comment by sickpig** [comment]
Wonder if we could find a solution that does not depends on `#ifdef BITCOIN_CASH` like we did for `src/buip055fork.cpp`. 

define a tweak or a global which value depends on  `#ifdef BITCOIN_CASH` and that is going to be used in all HF related helper to determine if we need to use cash code or not. 

e.g. `UpdateBUIP055Globals`: it returns false if `miningForkTime.value` tweak is set to 0 and the latter is set to 0 only of if `BITCOIN_CASH` is define: 
```c++
#ifdef BITCOIN_CASH
CTweak<uint64_t> miningForkTime("mining.forkTime",
    "Time in seconds since the epoch to initiate a hard fork as per BUIP055.",
    1501590000); // Tue 1 Aug 2017 12:20:00 UTC, uahf-technical-spec.md REQ-2
```

**Comment by ptschip** [comment]
@sickpig I thought about that, but the previous fork needed to have parameters defined and available before and during and after the fork whereas this one is strictly for the CASH chain hard forking. We can still define a tweak also if we need to,  but do we really need any of this code active on the BU legacy build?

**Comment by sickpig** [comment]
@ptschip yeah you are probably right but I was just envisioning how confusing the code will be once we are going to add the BIP146 and BIP 147, e.g. every time we need to do something like
```c++
    if (pindex->forkActivated(miningForkTime.value))
    {
        flags |= SCRIPT_ENABLE_SIGHASH_FORKID;
    }
#ifdef BITCOIN_CASH
    if (IsCashHFEnabled(config, pindex->pprev)) {
        flags |= SCRIPT_VERIFY_LOW_S;
        flags |= SCRIPT_VERIFY_NULLFAIL;
    }
#endif
```
and it seems odd that we use the same `ifdef` check in two different ways to.

**Comment by ptschip** [comment]
@sickpig I don't think the code will get confusing...once this hardfork is done then the protocol is upgraded and when the next hardfork happens, we don't have to keep the previous check anymore, but just absorb it into the protocol.  I don't think we ever need to have more than one hardfork check at a time....It's not like if there's a huge re-org we are going to go back to the old rules.  Once the upgrade has happened then that's it, afaics...maybe @gandrewstone can chime in as to how he  would like to handle each hardfork, but that's my two cents anyway.

**Comment by ptschip** [comment]
@sickpig I do see your point about the buildup of DEFINE's, @gandrewstone I wonder whether it makes more sense to rebase these forking PR's agains the CASH repo only...then we don't need defines at all and I think it actually makes more sense from the standpoint of running the travis tests...

**Comment by gandrewstone** [comment]
I'm hoping to keep it all mostly one code base.  I don't really like the #defines either, but I can live with it for this release until we refactor into somethng better.  

What I think we can do in the future is reorganize so that the chainparams and other cash related stuff is in a completely separate file.  In that case there might be some repetition of params that are common to bitcoin and cash.  But I think that's ok because its not really duplication -- is a completely separate chain that happens to share some common config values.

**Review by sickpig — APPROVED** [review]

**Pull request merged**
