### PR TITLE
[WIP, PORT] Address index support

### PR DESCRIPTION
**Pull request by awemany**
This is a port of a commit that was reworked by @Helvetian616 plus a couple simplifications and a simple RPC test on top. 

If anyone is not o.k. with the current attribution resp. blaming (I set the author of the commit to @btcdrak with a `Co-authored-by:` reference to @Helvetian616 as he was the one providing the commit I ported, over here: https://github.com/Helvetian616/BitcoinUnlimited/commit/20c8e5de6c95789ddf0b6fb91255c2802bb1e56d), please speak up!

@sickpig: I am unsure about correct attribution here.

### CODE REVIEW

**Comment by awemany** [comment]
This supersedes / closes #395, in case @Helvetian616 is fine with just dealing with the BCH variant of the addrindex. (Not dealing with anything BTC-related here)

**Comment by sickpig** [comment]
I'm ok with the current attribution

**Comment by ptschip** [comment]
needs rebase

**Comment by awemany** [comment]
@ptschip: Rebased.

**Comment by awemany** [comment]
And rebased again.

**Comment by awemany** [comment]
Closing this as it needs a lot of rework for CTOR that it probably makes more sense to rewrite it from scratch as soon as the fork happened and after the validation order code has been cleaned up.

**Pull request closed without merging**
