### PR TITLE
Fixed compiler warning.

### PR DESCRIPTION
**Pull request by AllanDoensen**
Minor fix of a compiler warning.

### CODE REVIEW

**Comment by gandrewstone** [comment]
what is the compiler warning?

**Comment by AllanDoensen** [comment]
CXX qt/test/qt_test_test_bitcoin_qt-paymentservertests.o qt/test/paymentservertests.cpp: In member function ‘void PaymentServerTests::paymentServerTests()’: qt/test/paymentservertests.cpp:65:6: warning: stack protector not protecting local variables: variable length buffer [-Wstack-protector] void PaymentServerTests::paymentServerTests() ^ CXXLD qt/test/test_bitcoin-qt

**Comment by AllanDoensen** [comment]
On Ubuntu 16.04 LTS.

**Comment by gandrewstone** [comment]
although this is not performance code, it pains me to not "keep-it-simple".  Consider using
enum { BIP70_MAX_PAYMENTREQUEST_SIZE = 50000 };
in paymentserver.h so this constant really is constant so we don't have to do memory allocation and cleanup.  If there's a compelling reason to no use an enum, we should wrap the allocation in a scoped pointer so it automatically cleans up if an exception is thrown.

**Comment by AllanDoensen** [comment]
removed

**Pull request closed without merging**
