### PR TITLE
[WIP] Keep cs_main unlocked as much as possible during AcceptToMemoryPoolWorker

### PR DESCRIPTION
**Pull request by ptschip**
This will make multi-threaded transaction processing more efficient and should improve throughput significantly.

### CODE REVIEW

**Comment by ptschip** [comment]
@gandrewstone FYI, the first commit is basically just 3 lines shown below, the rest is just indentation with no code changes (sorry i should have formatted at the end):

LEAVE_CRITICAL_SECTION(cs_main);
BOOST_SCOPE_EXIT(&cs_main) { ENTER_CRITICAL_SECTION(cs_main); }
BOOST_SCOPE_EXIT_END;

**Comment by sickpig** [comment]
linux 64bit is failing on `tx_clone.py`
linux 32bit is failing on `wallet.py`

**Comment by ptschip** [comment]
@sickpig thanks, I know, still a work in progress...

**Comment by sickpig** [comment]
ok great. good to know.

**Comment by ptschip** [comment]
@sickpig seems to have opened up a can of worms...  mempool.check() is failing.  Looks like the mempool and coinscache are getting into an inconsistent state.  This will take some time to sort through.

**Comment by ptschip** [comment]
closing for the time being

**Pull request closed without merging**
