### PR TITLE
Add bip68 activation heights to chainparams.cpp

### PR DESCRIPTION
**Pull request by ptschip**

### CODE REVIEW

**Review by sickpig — APPROVED** [review]

**Comment by sickpig** [comment]
Despite approval, I think we should remove or refacto `forkscsv_tests.cpp` to be based on height rather than version bits. I slightly prefer the former since we do not expose BIP 68 activation height via conf parameter.

**Comment by ptschip** [comment]
I still have to fix the tests

**Comment by gandrewstone** [comment]
Before I merge, can you do an verifying IBD from the genesis to make sure the chain syncs past these activation blocks?

**Comment by ptschip** [comment]
> Before I merge, can you do an verifying IBD from the genesis to make sure the chain syncs past these activation blocks?

done, sync completed...

**Pull request merged**
