### PR TITLE
Green Bitcoin Cash logo

### PR DESCRIPTION
**Pull request by Solon-Archon**
Change the Bitcoin Cash logo in the splash screen of BU to a green version. This is to help differentiate Bitcoin Cash enough from Bitcoin Core and make sure there is no/less confusion. Green is commonly associated with cash which is the number one property we are aiming for in Bitcoin Cash.

### CODE REVIEW

**Comment by sickpig** [comment]
@singularity87 thanks! 
I really do like to have an ad-hoc set of logos for BUCash. I just approved your PR. 
Wonder what other think about it (@gandrewstone, @ptschip, @awemany)?

**Review by sickpig — APPROVED** [review]

**Review by sickpig — CHANGES_REQUESTED** [review]
what about updating `bitcoin.icns` for MacOSX?

**Comment by sickpig** [comment]
@singularity87 sorry for the ambivalent comments I just made but I realize that we need to update also the `icns` file for MacOSX platform.

**Comment by ptschip** [comment]
@singularity87 nice work, but I think until there is a consensus in the community and industry to move to "green" for BitcoinCash then I think we should leave it as Orange.  For instance, Shapeshift is currently still using Orange...I think I saw a screen shot of what Bitpay was coming up with and they were using green in that but it hasn't been released.  So my own view is we should be followers in this instance.  Personally I'm also still somewhat attached to the Orange, but if it's to green then so be it.

**Comment by gandrewstone** [comment]
I asked @singularity87 to submit the PR because I like the idea.  It further distinguishes Bitcoin Cash from Bitcoin, and reinforces the "cash" idea (at least for US users, IDK if other countries associate green with money).

On the subject of waiting until we have a color/logo consensus, there is no standards body to make that happen in advance.  So we need to "emergent consensus" this which means that by switching, we encourage others to switch.  There is little harm done; we can always switch back if the "emergent consensus" ends up settling on orange.

Please comment with your opinion.  So far we've got 2 thumbs up and one down.

**Comment by Solon-Archon** [comment]
@sickpig I have added the icns version of the green logo on my fork of the repo. How do I add that change to this pull request? Is that possible?

@ptschip I appreciate your comments, but consensus is a continuous process. BU is a participant in the industry and is able to make its own decisions.

I understand the emotional/nostalgic connection with orange. I myself am attached to orange, but IMO we should be thinking practically. Sometimes we need to let the old ways go and look to the future.

**Comment by sickpig** [comment]
@singularity87 just push your changes (`git push`) and it should update the PR automatically

**Comment by Solon-Archon** [comment]
@sickpig I don't have git on my desktop. I only using github from my browser, and as you can probably tell I am not very proficient in using it.

**Comment by bitsko** [comment]
Orange.  Time and funding has already been invested in promotion of orange logo.  I love gold and green, but orange leads in recognition, changing the branding is expending efforts on reinventing something.

The community has made excellent memes involving green, and the contrast to orange is helpful, but the inertia and economic sense is with orange in facing the wider public.

Green is the color of the flippening.  

Orange:
bitcoincash.org 
bitcoinabc.org 
bitco.in 
bitcoinunlimited.info
bitcoinxt.software

bitcoin.com? (is that yellow or orange?) roger ver: 'I don't think its ever going to turn green' (AMA)

**Comment by Solon-Archon** [comment]
@bitsko Yes, it takes effort, and that is what we are discussing. We are discussing expending effort to improve the branding of Bitcoin Cash. If it had been left to ABC we would still have a logo that looks, for all intents and purposes, identical to the old Bitcoin logo. There are a number of very practical reasons why we need a green/non-orange logo.

For example, Icons are often square on websites. An orange rectangular logo does not fit in a square space well, therefore people will either end up using the orange logo as a circle, which looks identical to the Bitcoin Core logo, or they will use the green logo anyway.

The Bitcoin community made many many mistakes with its branding over the years and we should be doing what we can to not make similar mistakes.

I know some people think using green would be 'giving up the bitcoin brand', but we already lost the Bitcoin brand. Core took it. They won on this point, and trying to add confusion by looking identical to them is not going to help anybody, least of all Bitcoin Cash. We need to realise that Bitcoin is probably going to die in the next year, or stumble on causing problems for all users and businesses, and being associated with that is only going to harm our branding. Go look in the issues section on github for the main Bitcoin wallets and you'll see what a total mess it already is.

**Comment by bitsko** [comment]
> We are discussing expending effort to improve the branding of Bitcoin Cash.

I disagree with it being defined as an improvement without wider support on the highest traffic bitcoin cash websites.

>For example, Icons are often square on websites. An orange rectangular logo does not fit in a square space well, therefore people will either end up using the orange logo as a circle, which looks identical to the Bitcoin Core logo, or they will use the green logo anyway.

I agree that in the short term a green logo is an excellent contrast.  However how long do you think retail is going to be offering an unusable asset for exchange? Businesses should be dropping legacy support as the upgraded version gains popularity and use.  With the exception of exchanges, these coins have wildly divergent paths and don't see how they will be sharing the same UI space for long...

I think the inertia behind the orange branding is so great and the desire to reverse a quite trivial past decision can rightly be seen as bikeshedding. Green imagery is awesome keep it up but I don't support changing the flag.

**Comment by Solon-Archon** [comment]
Bitcoin.com's branding is yellow, not green or orange. If you go into the bitcoin.com wallet they display Bitcoin Cash as green. Why do they do this? Out of necessity, obviously. This is true across many different websites.

We basically have two choices. Forever remain both green and orange and without a cogent marketing strategy, or actually come together and implement one colour. Some people will need to swallow their pride to do this, but it is in the interest of the industry.

How much effort do you think it would be to update those 5 sites you listed? It could be done in a day, easily.

**Comment by gandrewstone** [comment]
@bitsko, in the emergent consensus decision making paradigm, its not the big guys that change first.  They are more conservative.  The little guys change first and then possibly drive the bigger change.  In this case, changing the BU Cash edition logo is a very small change and unlikely to create confusion, since the client self-identifies anyway.  Also since we are a client of BU cash we are actually changing our own logo, not the Bitcoin cash logo (notice the infinity shadow -- we've already changed the logo from the stock Bitcoin one).

So when I hear you say that you love the green logo but don't change it because these other places have not done so, I'm not enthralled by that conservatism.

I actually think that it will REDUCE confusion when people are running multiple desktop clients, because icons are small on the desktop and menu bar.  Tilting the B is unnoticeable, the brackets are visible but I think that they easily misunderstood as some kind of rendering error.  However, a green logo really stands out.

**Comment by Mengerian** [comment]
I vote for sticking with sticking with orange.

I think most people are happy with the orange logo, they just don't want to waste their time arguing about it.

I also just think the orange looks better.

**Comment by AndrewClifford** [comment]
I have been thinking about this for a few weeks, and have come around to the view that the green "bill"-style logo is preferable. There are now tens of thousands of people entering cryptocurrency as new investors and users, who are being won over by this paradigm shift in money.
The very first thing they see is symbology. Bitcoin Cash might claim to be the Bitcoin of Satoshi's vision, but it does need some differentiation, and the orange logo is too similar. We are on the inside so we are easily aware of small differences.
One other thought is that _if the chain-death actually happens_, there will be enormous bad press for Bitcoin BTC. Bitcoin Cash needs to be in clear water to be seen as the future, not part of a failed experiment. A green logo is a small compromise from old-timers to the millions of newcomers.

**Comment by ptschip** [comment]
@AndrewClifford   Well said, however, and perhaps I'm wrong, I don't
agree that changing the color is going to differentiate us enough in the
event of a chain death of Bitcoin, and I'm not convinced it's even
important. And I do agree with Mengerian that Orange is just a better
color;  From the view of color theory, Orange is warm (the warmest of
the colors), bold and stands out visually, Green is cold and visually
recedes...if you scroll through the list of icons from
https://coinmarketcaps.com  you can get a quick view of your own
reponses to the various colors of each coin.  I think you you'll find
the orange icons (and to a lesser extent red) stand out quite clearly
while green (such as Tether) are rather neutral and dull in comparison. 
Of course to be fair, there are also various shades within each color,
and the one chosen by Tether is quite awful...the green one for the BU
icon is much brighter (less neutral) and well chosen in my opinion; If
we're going green then I think this PR has done it right.

As we see here in our own small community, there are some rather
surpisingly strong feelings about changing the color branding - which
just confirms to me how important branding is in crypo.  Maybe I'm being
too conservative but I'd rather go slow, (slow in terms of weeks) to get
people used to the idea of this change (potential change) rather than
risk some sort of unexpected backlash. Perhaps we should at least make
an informal BU or Reddit poll to introduce the idea and  to the wider
community and get feedback?

**Comment by bitsko** [comment]
>So when I hear you say that you love the green logo but don't change it because these other places have not done so, I'm not enthralled by that conservatism.

I tend to be conservative in budgeting and effort.  I consider orange as 'work already completed'.  And the effort to change the brand as one to unnecessarily repeat actions.  Although on the scale of things I find it rather trivial, and if I woke up tomorrow with a fully green bitcoin cash, I would not be upset in the slightest.

Orange has an established history.  Reducing confusion is a compelling argument to redo all the branding, wipe the network effect of brand recognition away and start all over.  But should we then not reconsider the name, which causes the most confusion?  I was given an example this morning of a business operator wanting to drop bitcoin because of the fees and not wanting to replace it with bitcoin cash due to the confusing name.  Particularly with the same address format presently this is confusing.

So how about turn the brand green and change the name to something else too like 'cash'.. that would be the most ideal way to avoid confusion, would it not?  Or is it that one wishes to keep the name 'bitcoin' in order to leverage that brand... if so then is not the color orange in the same situation, of leveraging brand?

 I think as you explore the opinions of the site holders promoting orange there is a chance that they have already been propositioned to change to green and have resisted such a change and so the notion that they would all change too may be much more difficult than a brand changing effort in a decentralized community would want.

So the simplest way to have unity is to stick with the incumbent branding.

> From the view of color theory

This is what is lacking, a decent exploration of cognitive science and branding... we have an orange rectangle put forth originally (same color different shape)  and we have a green circle commonly put forth (best example neon and tilt left, unfortunate example puke green and tilt right).. so same shape and different color.

https://psychology.stackexchange.com/questions/4495/what-is-the-relative-importance-of-shape-and-color-in-object-recognition/

What's more powerful to recognition, shape or color? which takes prescience in the mind when someone is scanning logos? I tried to search and couldn't find much in a short time at least.  But its this sort of analysis that can pull this effort out of what could be seen as mere bikeshedding imo.  Best of luck to you all on this issue that should be taken somewhat lightly.

**Comment by Solon-Archon** [comment]
@ptschip I'm all for polls.

**Comment by Mengerian** [comment]
Just to expand slightly in my comments, I'm fine with people making green logos if they want to, and if they think it looks cool. I agree with Rick Falkvinge's approach of letting people do what they they as part of a shared goal to make Bitcoin Cash successful.

That being said, I think it's unrealistic to expect that everyone will want to switch to a green logo, and a campaign trying to convince people to do so would stir up conflict and be counterproductive. I'm wary that BU switching to a green logo could be part such a larger campaign, and that would not be in the interests of BU, or Bitcoin Cash.

Also, @singularity87 when you say " If it had been left to ABC we would still have a logo that looks, for all intents and purposes, identical to the old Bitcoin logo", I'm not sure exactly what you're alluding to, but it comes across as veiled criticism of ABC. I see ABC as the offspring of BU. It's fine to offer advice and feedback, but, as a good parent, I think that BU should avoid being overly critical and should instead lead by example and be proud of ABC's accomplishments.

**Comment by Solon-Archon** [comment]
@Mengerian It's not a thinly veiled criticism. It's just a criticism. Are we not able to be critical of anything anymore? Every reasonable person should welcome both positive and negative feedback. The original plan for the BCH logo was the Bitcoin logo just tilted the other direction. If our aim is to be purposely confused with the BTC logo then let's just say this outright. That's our marketing strategy, to confuse people into thinking we are the same thing.

IMO this is a terrible strategy for the numerous reasons I, and many others, have already stated. Using this strategy, the logo will always be represented as both green and orange, because the UI of certain apps and websites necessitates enough differentiation so that their users are not confused. These sites/apps will simply use green as they don't care about our ideological arguments. They care about their customers.

The only hope we have of having a unified colour across the industry is to use green, of which there is no opposition from non-bitcoin-cash-specific businesses.

I would also like to add that after three different poles (arguably 4 if you include reddit) green has been the clear winner by a significant margin.

https://twitter.com/BitcoinCashFans/status/942170097275121664
https://twitter.com/__pcd__/status/943124196225318912
https://twitter.com/__pcd__/status/933177787262865408

EDIT: I've been informed that the square around the circle was always there from the beginning. This is my mistake and I apologise about this. I remember often seeing it without, I assume because quite a few sites use the circle-only logo.

**Comment by gandrewstone** [comment]
looks like coinbase/gdax is going green (https://blog.coinbase.com/buy-sell-send-and-receive-bitcoin-cash-on-coinbase-65f1b2c7214b)

**Comment by ptschip** [comment]
yup, looks like green has got my vote now :)

**Comment by Mengerian** [comment]
@singularity87 OK, now I see where we're getting our wires crossed. I think you have a mistaken impression that people involved with Bitcoin ABC want to confuse people between BCH and BTC. If that were true, it would certainly be a valid criticism. But I don't think it is true.

You said: "The original plan for the BCH logo was the Bitcoin logo just tilted the other direction"

I don't know where you got that idea, but it's not accurate. The first ever Bitcoin Cash logo created was pre-Aug 1st at https://www.bitcoinabc.org/

It's the "orange flag" logo. In fact you can still see it there, as it has been unchanged since day 1, on the hastily-created bitcoinabc.org Wix site.

**Comment by Solon-Archon** [comment]
@Mengerian See my EDIT at the bottom.

**Comment by Mengerian** [comment]
@singularity87 thanks for the adding in the correction :)

Regarding green/orange, I don't have a very strong opinion. But what I think it most important is to avoid some sort of conflict in the community over this. So when I see one or the other being promoted very forcefully, I just don't want the argument to escalate unnecessarily. We're all passionate about making Bitcoin Cash successful.

Looks like Coinbase is using green, so maybe that will be the trend. Maybe orange is better, or maybe everyone converging to green is better. But far more important than both of those is that we don't divert our energy into conflict with each other over this issue.

**Comment by gandrewstone** [comment]
I think that opinion was leaning towards green or at worst pretty even.  So with other companies and media outlets moving towards green, I feel that my initial opinion that we should give it a try is confirmed.  Green seems good both on its own merits and to support singularity's great energy towards much needed BCH outreach/marketing!  Orange lovers, if the whole community moves back to orange we'll certainly do so as well.  Thanks for everyone's input (and of course you can raise a BUIP to force a vote if you feel very strongly about the issue).

**Comment by JollyMort** [comment]
I love green, it "smells" right. Improved the blocksize, improved DAA, improved the logo. Still Bitcoin, Bitcoin Cash. Both BTC and BCH are Bitcoin, the era of only 1 is forever over. That is fact. Pretending there can ever again be only "the one" won't help anyone. I love this 'everyone pick a logo they want' with BCH, it shows the decentalized nature well. But still, if anyone asks - green. It looks better, and is more attractive to me. Makes me want the damn thing.

Edit: sorry for necrobump, damn Reddit brought me here

**Pull request merged**
