### PR TITLE
Implement two more ban reason codes

### PR DESCRIPTION
**Pull request by ptschip**
BanReasonInvalidInventory for incorrect or null inventory messages

and

BanReasonInvalidPeer or BitcoinSV peers or any other peer deemed
invalid.

### CODE REVIEW

**Review by sickpig — APPROVED** [review]

**Comment by ptschip** [comment]
added one more item, now it's done.

**Comment by gandrewstone** [comment]
../../src/test/DoS_tests.cpp:154:100: error: no matching function for call to ‘CDoSManager::Ban(CSubNet, BanReason, const unsigned int&, bool)’

     dosMan.Ban(CSubNet("10.168.1.0/28"), BanReasonManuallyAdded, DEFAULT_MISBEHAVING_BANTIME, false);

                                                                                                    ^

In file included from ../../src/test/DoS_tests.cpp:9:0:

../../src/dosman.h:89:10: note: candidate: void CDoSManager::Ban(const CNetAddr&, const string&, const BanReason&, int64_t, bool)

     void Ban(const CNetAddr &ip,

          ^~~

../../src/dosman.h:89:10: note:   no known conversion for argument 1 from ‘CSubNet’ to ‘const CNetAddr&’

../../src/dosman.h:94:10: note: candidate: void CDoSManager::Ban(const CSubNet&, const string&, const BanReason&, int64_t, bool)

     void Ban(const CSubNet &subNet,

          ^~~

../../src/dosman.h:94:10: note:   no known conversion for argument 2 from ‘BanReason’ to ‘const string& {aka const std::__cxx11::basic_string<char>&}’

**Comment by ptschip** [comment]
putting into WIP, have to fix something.

**Comment by ptschip** [comment]
taking out of WIP

**Pull request merged**
