### PR TITLE
apply formatting rules to additional files

### PR DESCRIPTION
**Pull request by BitcoinUnlimitedJanitor**

### CODE REVIEW

**Comment by kyuupichan** [comment]
Most ports from Core now fail to apply, and the whitespace issues in main.cpp in particular have been painful to work around without noise cleaning them up, so I support this.

**Comment by kyuupichan** [comment]
But it would be nice if at least some of the pending PRs on dev that touch these files were cleared first

**Review by ptschip — APPROVED** [review]
looks good.

**Comment by gandrewstone** [comment]
Every time I try to clear off PRs, new ones get added.  I'm sorry for the inconvenience, but we just need to do this.

**Pull request merged**
