### PR TITLE
add centos build to travis

### PR DESCRIPTION
**Pull request by Greg-Griffith**

### CODE REVIEW

**Comment by Greg-Griffith** [comment]
i added NO_QT to this build to reduce build time because it kept timing out. I don't consider having QT included critical since the rpm build is aimed at developers and businesses.

**Comment by Greg-Griffith** [comment]
request review @sickpig

**Review by sickpig — COMMENTED** [review]
using `add rpm build to travis` as a commit tittle seems to indicate we are building BU rpm packages for distribution rather than testing the build process on rpm/yum based distro like centos.

A part from that I'm ok with the changes.

**Comment by Greg-Griffith** [comment]
what is your suggested change to the title?

**Comment by sickpig** [comment]
What about "add centos build to travis"?

**Pull request merged**
