### PR TITLE
Source image location and splash screen

### PR DESCRIPTION
**Pull request by gandrewstone**
Create cleaner splash screen, and add contrib/images directory to hold the source images used to create the images and icons in the client.

### CODE REVIEW

**Comment by gandrewstone** [comment]
Splash screen looks like this: https://supload.com/HylxqmgrSz

**Comment by sickpig** [comment]
@gandrewstone 
formatting problems 
https://travis-ci.org/BitcoinUnlimited/BitcoinUnlimited/jobs/332521398#L736

**Review by ptschip — APPROVED** [review]

**Comment by jcramer** [comment]
How come on my Mac the splash screen looks like this?

image

**Comment by sickpig** [comment]
@jcramer this is the same issue reported in https://github.com/BitcoinUnlimited/BitcoinUnlimited/issues/954

guess you are using 1.3.0.1, am I right?

**Comment by jcramer** [comment]
Yes, 1.3.0.1.  Thanks, I figured there was another issue about it, just wanted to double check.

**Pull request merged**
