### PR TITLE
Udpate qt depends

### PR DESCRIPTION
**Pull request by sickpig**

### CODE REVIEW

**Comment by sickpig** [comment]
need to find a way to make travis to save the dependencies built before timing out, so that in subsequent run travis could reuse that artifacts rather than restart the build process from scratch.

**Comment by sickpig** [comment]
Rebase on top of #1559 so that we could hope to have travis finish its job in time without timing out.

**Comment by sickpig** [comment]
Sees like I run into a link problem. Basically the build process ends up with this series of errors: 

```
$> make                            
Making all in src                                                                                                                                                                                        
make[1]: Entering directory '/home/sickpig/src/bu-sickpig/src'                                                                                                                                                                                    
make  all-recursive                                                                                                                                                                                              
make[2]: Entering directory '/home/sickpig/src/bu-sickpig/src'                        
make[3]: Entering directory '/home/sickpig/src/bu-sickpig/src'                                                                                                   
  OBJCXXLD qt/bitcoin-qt                                                                                                                                                                                                    
/home/sickpig/src/bu-sickpig/depends/x86_64-pc-linux-gnu/share/../lib/libQt5FontDatabaseSupport.a(qfontconfigdatabase.o): In function `QFontconfigDatabase::defaultFont() const':                                                     
qfontconfigdatabase.cpp:(.text+0x60): undefined reference to `FcPatternCreate'                                                                                                                                                       
qfontconfigdatabase.cpp:(.text+0x6b): undefined reference to `FcDefaultSubstitute'                                                                          
qfontconfigdatabase.cpp:(.text+0x87): undefined reference to `FcPatternGetString'      
qfontconfigdatabase.cpp:(.text+0x8f): undefined reference to `FcPatternCreate'                                                                                                                                   
qfontconfigdatabase.cpp:(.text+0xaa): undefined reference to `FcPatternAddString'   
qfontconfigdatabase.cpp:(.text+0xb6): undefined reference to `FcConfigSubstitute'                                                                                                                          
qfontconfigdatabase.cpp:(.text+0xbe): undefined reference to `FcDefaultSubstitute' 
qfontconfigdatabase.cpp:(.text+0xdd): undefined reference to `FcPatternGetString'                                                                                    
qfontconfigdatabase.cpp:(.text+0x10e): undefined reference to `FcPatternDestroy'                                                                                                                                      
qfontconfigdatabase.cpp:(.text+0x116): undefined reference to `FcPatternDestroy' 
...
...
qfontengine_ft.cpp:(.text+0x743b): undefined reference to `FT_New_Face'
/home/sickpig/src/bu-sickpig/depends/x86_64-pc-linux-gnu/share/../lib/libQt5FontDatabaseSupport.a(qfontengine_ft.o): In function `QFontEngineFT::xHeight() const':
qfontengine_ft.cpp:(.text+0x7ee9): undefined reference to `FT_Get_Sfnt_Table'
/home/sickpig/src/bu-sickpig/depends/x86_64-pc-linux-gnu/share/../lib/libQt5FontDatabaseSupport.a(qfontengine_ft.o): In function `QFontEngineFT::averageCharWidth() const':
qfontengine_ft.cpp:(.text+0x8009): undefined reference to `FT_Get_Sfnt_Table'
/home/sickpig/src/bu-sickpig/depends/x86_64-pc-linux-gnu/share/../lib/libQt5FontDatabaseSupport.a(qfontengine_ft.o): In function `QFontEngineFT::addOutlineToPath(double, double, QGlyphLayout const&, QPainterPath*, QFlags<QTextItem::RenderFlag>)':
qfontengine_ft.cpp:(.text+0x8383): undefined reference to `FT_Load_Glyph'
collect2: error: ld returned 1 exit status
Makefile:4011: recipe for target 'qt/bitcoin-qt' failed
```
```

**Comment by sickpig** [comment]
linker problem has been fixed in 34ecb8e

PR is ready to go IMHO

**Comment by gandrewstone** [comment]
@sickpig needs rebase

**Comment by sickpig** [comment]
@gandrewstone rebased done.

**Pull request merged**
