### PR TITLE
Add a config for max transaction fees

### PR DESCRIPTION
**Pull request by deadalnix**
This avoid doing stupid mistakes. Backport from Core.

### CODE REVIEW

**Comment by gandrewstone** [comment]
If you convert maxtxfee to a "CTweaks" variable then we will get the ability to change the value via bitcoin-cli for free.  But about 90% of this PR remains the same -- using CTweaks basically only affects the object construction and initialization.

**Comment by deadalnix** [comment]
It is a CTWeak now.

**Comment by deadalnix** [comment]
Ping ?

**Comment by gandrewstone** [comment]
sorry, thanks for pinging me and for converting to a CTweak

**Pull request merged**
