### PR TITLE
Kill RBF.

### PR DESCRIPTION
**Pull request by deadalnix**
Any feature helping double spend has nothing to do in a p2p cash system.

### CODE REVIEW

**Comment by ftrader** [comment]
I have looked over the code, and the changes seem sensible, `make check` passes, and `listtransactions.py` below also still passes, which is of slightly surprising to me given that actual RBF code was removed.

However, I still detect leftovers which seem to be related to RBF code in these files that could be cleaned up:

src/policy/rbf.{h,cpp}
src/wallet/rpcwallet.cpp
src/Makefile.am
qa/rpc-tests/listtransactions.py

**Comment by deadalnix** [comment]
The leftover are about generating RBF txs in the wallet. This removes RBF from the node code, not the wallet code.

The fact that this doesn't break any tests is because Core is the absolute most well tested and peer reviewed software in the world, and has engineering standards that would put Google, Facebook and Apple combined to shame. You just can't understand it because you aren't wizzard enough.

**Comment by ftrader** [comment]
>This removes RBF from the node code

PR title and intro comment sounded pretty complete about exterminating it. Maybe consider if we still need to generate those txs if our node does not intend to support them. Me - I don't see the point in keeping that code if the aim of the PR is to completely eliminate RBF in the software.

**Comment by stefment** [comment]
you sound crazier than luker-jr fyi. no offence to luke.

anyway double spends have their place. for example if your tx is stuck and you want to spend it again with a higher fee.

keep in mind bitcoin core is open source, so if you know of any vulnerabilities or the like and you dont report them, the responsibility of an eventual failure from this falls on you.

**Comment by ftrader** [comment]
@stefment : in the hopes of you learning how to use your time constructively:

http://oss-watch.ac.uk/resources/toptipscommunities

I would also encourage you to track the PR's on this project more closely, so you know what's in the works (e.g. CPFP). You could have saved yourself a ragepost.

**Comment by stefment** [comment]
Thanks for the link but i think i will pass.

**Comment by deadalnix** [comment]
Can we move on with that ? It's been a week and there is no real opposition and I got to fix merge conflict already.

@ftrader It'll get removed from the wallet as well, it is completely independent from this.

**Comment by ftrader** [comment]
It's not me blocking this - if you had replied earlier saying there is a plan to remove the rest, the conversation could have moved on and probably this would be merged already.

Anyway, to restate my point - I'm fine with the changes in this PR, it can be merged from my point of view.

**Review by ftrader — APPROVED** [review]

**Comment by deadalnix** [comment]
I'm not sure why I should mention that there are changes unrelated to this PR coming to get this PR moving. This is not a healthy way of moving forward here.

**Comment by ftrader** [comment]
I previously wrote:

>Maybe consider if we still need to generate those txs if our node does not intend to support them.

You never replied to that until today's clarification of intentions to address this separately.
So I assumed you were busy on other stuff. What's the timeout I need to use to ping you when you miss a question?

**Review by kyuupichan — COMMENTED** [review]
Agree with the principle and the changes look good.  I've not tested.

**Comment by deadalnix** [comment]
That would have been great to merge this BEFORE reformating main.cpp . But anyway, it's there.

**Comment by gandrewstone** [comment]
guys, please bring your reviews to a conclusion... yes or no.  If I see engineers having a conversation, I will delay the merge if I have other high priority items.

[Although this PR seems to essentially remove previously commented out code, so I am a bit surprised at the discussion]

**Review by kyuupichan — APPROVED** [review]
Builds, makes check; running on testnet here.

**Comment by deadalnix** [comment]
You are the only one with merge right and refuse to delegate so you have no higher priority items. If you did you'd be delegating this.

**Comment by gandrewstone** [comment]
@deadalnix, actually clicking the merge button is the most trivial portion of the work required.  If I see that other engineers are actively reviewing a PR and have approved a PR, then I may personally make a less thorough review.  Especially for changes like this one which is mostly commenting out dead code.  

But for this to be effective, I need those engineers to actually approve a change rather than the discussion just trail off...

**Pull request merged**
