### PR TITLE
More Accurate Project Branding

### PR DESCRIPTION
**Pull request by yourhydra**
This pull request changes "Bitcoin Unlimited" to "Zero-Confirmation StarbucksCoin," improving the transparency this project. All project files have been updated for easy acceptance!

### CODE REVIEW

**Comment by sandakersmann** [comment]
Great :D We need more accurate branding in this space. You should make a pull request to rebrand Bitcoin Core to CrippleCoin as well ;)

**Comment by ptschip** [comment]
lol - you gave me a chuckle there...hopefully you didn't edit all those
files by hand...

**Comment by deadalnix** [comment]
You forgot to rename the unlimited.h and unlimited.cpp files. I'm very disappointed by such sloppy coding. I was told core has all the best dev and you guys let us down like this...

**Comment by leafcutterant** [comment]
ACK

**Comment by yourhydra** [comment]
only crippled for starbucks purchases ;)







For the secrets and lies, my PGP key:
https://libbitcoin.dyne.org/julia_tourianski.pgp.asc

**Comment by juscamarena** [comment]
Wait gandrewstone. Did that close gain consensus? I thought we all EC on the name change.

**Comment by grubles** [comment]
Bitcoin Unlimited devs closed this PR??? I **will not** stand for this censorship!

**Comment by anduck** [comment]
What is the reasoning to close this PR? The idea in this PR is very good. Separate BU from Bitcoin, why not? As we all know, BU has different rules than Bitcoin. Maybe it is time to clarify that BU is an altcoin.

**Pull request closed without merging**
