### PR TITLE
[port] Specialized double-SHA256 with 64 byte inputs with SSE4.1 and AVX2

### PR DESCRIPTION
**Pull request by sickpig**
this is a port of bitcoin/bitcoin/pull/13191

it is built on top of #1997 

Later on also bitcoin/bitcoin/pull/13393 and /bitcoin/bitcoin/pull/13386

### CODE REVIEW

**Comment by ptschip** [comment]
needs rebase

**Comment by sickpig** [comment]
taking out of WIP (problem was that during last rebase a scripted diff commit was applied twice)

**Comment by sickpig** [comment]
failing compiling due to: 

```
In file included from /usr/lib/gcc/x86_64-linux-gnu/7/include/x86intrin.h:39:0,
                 from ../../src/crypto/sha256_sse41.cpp:7:
/usr/lib/gcc/x86_64-linux-gnu/7/include/tmmintrin.h: In function ‘__m128i sha256d64_sse41::{anonymous}::Read4(const unsigned char*, int)’:
/usr/lib/gcc/x86_64-linux-gnu/7/include/tmmintrin.h:136:1: error: inlining failed in call to always_inline ‘__m128i _mm_shuffle_epi8(__m128i, __m128i)’: target specific option mismatch
 _mm_shuffle_epi8 (__m128i __X, __m128i __Y)
 ^~~~~~~~~~~~~~~~
```

not able to reproduce locally, will investigate further.

**Comment by sickpig** [comment]
ok I was able to reproduce it locally by using this `configure` flags:

`--enable-debug --enable-glibc-back-compat --enable-reduce-exports`

**Comment by sickpig** [comment]
taking out of wip, prev problem fixed

**Pull request merged**
