### PR TITLE
Use C++11

### PR DESCRIPTION
**Pull request by deadalnix**
Just compile the project with C++11 instead of 98. This will allow to use the C++11 goodies.

### CODE REVIEW

**Comment by ptschip** [comment]
@deadalnix   it doesn't look like travis ran a build/test on this PR for some reason.

**Comment by sickpig** [comment]
@ptschip @deadalnix  see
https://travis-ci.org/BitcoinUnlimited/BitcoinUnlimited/jobs/184278197#L965

to make a long story short our Travis-ci is using ubuntu 12.04 (precise) and it seems that the compiler they are using does not support C++11

I'm already working on migrating travis to ubuntu 14.04, once this is ready and merged the issue will be fixed.

**Comment by gandrewstone** [comment]
I had to fix c++11 issues on ARM and MAC machines:
1. boost copy_file undefined symbol (google it).  I fixed by not using copy_file
2. decl that uses list with a pre-declared class doesn't work on clang: i.e: class foo; void fn(list<foo>& f); give you an error. I fixed by moving decls around.
3. a few more LONG_LONG_MAX

I have not tested on windows, but am merging so someone with a windows build set up can try it.

**Comment by sickpig** [comment]
@gandrewstone from now on we couldn't use Travis anymore cause currently we are not supporting C1++.

to get it working we need to update it to use Ubuntu trusty rather than precise.

**Comment by gandrewstone** [comment]
unfortunately I merged before I noticed your comment... let's talk about it on slack

**Comment by deadalnix** [comment]
Ha yes, this probably shouldn't have been merged without travis being happy about it :(

**Comment by sickpig** [comment]
@deadalnix @gandrewstone 

A little update. 

So I'm trying to update our Travis conf to work with Ubuntu trusty. The work is based on a branch of mine you could find here: https://github.com/sickpig/BitcoinUnlimited/tree/test/travis-ci

Apart from the switch to Ubuntu 16.04 a bunch of other things are included, e.g. a proper out-of-tree build for all the projects dependency. 

Unluckily as you could from this travis session: 

https://travis-ci.org/sickpig/BitcoinUnlimited/builds/184666539

`make check` fails apparently with this error message:

```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
  what():  boost unique_lock owns already the mutex: Resource deadlock avoided
```
(see https://travis-ci.org/sickpig/BitcoinUnlimited/jobs/184666544#L3205)

the cause seems to be related to one core had here: 

https://github.com/bitcoin/bitcoin/issues/8260

What's worst is that the issue was closed without a proper solution a part from mentioning that a fix has been committed to the 0.13 branch.

They said that the bug was fixed in the branch 0.13 but do  not report the specific commit. 

@deadalnix any idea on how to fix it?

**Comment by sickpig** [comment]
@gandrewstone I propose to revert the PR and plan the migration to c++11 after the new release.

**Comment by deadalnix** [comment]
This is breaking the build and no solution is know atm. This should not have been merged in the first place, and should be reverted in a timely manner.

**Comment by ptschip** [comment]
I also agree with backing it out.

**Comment by gandrewstone** [comment]
Ha! I rushed this one because deadalnx's prior PR has been delayed a loong time...

But this is strange because I got good builds and runs on ARM linux, intel linux, and MACs, with a couple of changes.

But I will back it out, please use the "deadalnix-cpp11" branch as the base for subsequent PRs for this feature

**Comment by sickpig** [comment]
@gandrewstone with this PR applied the code build successfully, what it is failing is the `make check` step.

**Comment by deadalnix** [comment]
Make check passed on my machine and I assume on his as well. It must be
some stupid problem like if you use this version of gcc with that version
of boost, then this weird stuff happens.

**Pull request merged**
