### PR TITLE
Activate the new DAA by height instead of MTP

### PR DESCRIPTION
**Pull request by sickpig**

### CODE REVIEW

**Comment by gandrewstone** [comment]
This comment is perhaps bigger than this PR, but:

 We will likely have hard forks twice a year.  It makes sense to come up with a system to handle these that reuses as much code as possible.  We could re-use the MTP logic for every new hard fork and then post HF have an almost-mechanical process that we use to convert the code to a block height, freeing the MTP logic up for the next HF.  This would also help our testing -- if the MTP HF variable name does not change, we can keep the same test framework that "rocks" back and forth over the upcoming HF.  

And some kind of naming convention that presumes multiple hard forks would really help.  Today we use comments and variables like "the hard fork", or "new DAA" which will become ambiguous quickly.

**Comment by gandrewstone** [comment]
Also, please indicate the testing that you have done.  I'd like at a minimum to see that a blockchain sync was done.  And I'm open to any suggestions as to how we'd unit test moving across the fork... it seems pretty much impossible given that we can't sync mainchain as part of a unit test.

**Comment by sickpig** [comment]
@gandrewstone:

WRT having a code machinery in place to implement the 2 HFs per year plan.

WRT test done on this PR: I made two manual tests (nothing you can do in automatic fashion thou):

1. stop a synced up-to-date node, install the new `bitcoind` based on PR, restart it, invalidate a block that has an height lower than the fork height, reconsider the block, and check if the new `bitcoind` follow the correct chain once it reached the fork point. 

2. sync a new node from scratch 

Another think tha we could try is something like: 

1. stop the node, install the PR code
2. remove enough `blk*.dat` to get in a pre state fork 
3. restart the node

(dunno if we need to remove some files in the `chianstate` dir thou) 

As a last point I really do think that we should also update main chain checkpoint to include the height of every successful HF we deployed.

**Comment by sickpig** [comment]
@gandrewstone is the test I've done enough or do you want something more?

**Comment by gandrewstone** [comment]
That's enough testing, thx! Merged

**Pull request merged**
