### PR TITLE
[Backport] Fix Qt Segfault

### PR DESCRIPTION
**Pull request by kyuupichan**
Core PR bitcoin#8540.

### CODE REVIEW

**Comment by gandrewstone** [comment]
I have noticed that you also get a segfault if you specify a data directory on the command line that is not writable, (owned by another user, for example).  Do you have time to take a look at this issue, and try to break it in similar ways, and fold the fixes into this PR?

**Comment by kyuupichan** [comment]
Sure I can give it a go. It'll take a day or two.

**Comment by kyuupichan** [comment]
Though I'd prefer to perhaps do that as a separate PR if you don't mind and have no objection to this.  I'll open an issue; perhaps you can assign it to me?

**Comment by gandrewstone** [comment]
sure you can do it as another PR.  thanks for contributing!

**Pull request merged**
