### PR TITLE
Add GUI tab Top Public Labels via startup command -toppubliclabels

### PR DESCRIPTION
**Pull request by marlengit**
This gui PR contains features to display the Top Public Labels in the blockchain, grouping UTXOs that have matching public labels and ranking them by the aggregated unspent amounts aggregate. This facilitates user voting so that BCH stakeholders can communicate with other stakeholders via the blockchain. Stakeholders move the most important messages to the top of the rankings by sending txs using the public label they wish to promote higher. The UTXO amount will be applied in aggregate with other UTXOs that have matching public labels. Since all messages are in the blockchain all messages and rankings are 100% verified by the client. Just like bitcoinvoice.io but all done in the BU client so no need to trust a 3rd party website for the results. 

The command line parameter is -toppubliclabels <n> where n is the minimum number of satoshis to track for public labels. Public Labels with UTXO amounts below this value will not be tracked. Upon first startup the wallet will do a rescan to populate the wallet file with the all public labels that have UTXO amounts greater than this value. The txindex=1 must also be turned on for top public labels to be tracked. 

Further there is a hard code in the tab list which will only display the Top 20 public labels for any filter. Its probably a good idea to create a special conf file which contains a special wallet and -toppubliclabels startup. 

Example toppubliclabels.conf:
txindex=1
toppubliclabels=10000000
wallet=wallet.toppubliclabels.dat

### CODE REVIEW

**Comment by sickpig** [comment]
@marlengit the list of commits seems rather strange to me, a lot of merge commits that shouldn't be there. Seems like you based your work on some old-not-up-to-date `dev` branch. 

I looked at https://github.com/marlengit/BitcoinUnlimited/commits/dev_gui_top_public_labels

and the situation seems a lot better, in fact those are the commits on to of dev that you implements to develop the feature: 

- Add display of earliest Top Public Label datetime.
- Add some fixes for Top Public Labels tab.
- Add Top Public Labels filter for Top 20.
- Top Public Labels fix shortcut menu and map filter.
- Top Public Labels tab various fixes. 

the most recent commit though is a merge commit w/ subject `Merge branch 'dev' into dev_gui_top_public_labels, I think this is the reason why you end up with a so strange list of commits in this PR. 

Why didn't you use a `rebase` rather than a `merge` ? 

I think that if you remove the last commit of yours in `dev_gui_top_public_labels`, i.e. : 

```sh
git checkout dev_gui_top_public_labels
git reset --hard HEAD^
```

then you could rebase your branch on top of current `dev` 

```sh
git checkout dev_gui_top_public_labels
git fetch upstream 
git rebase upstream/dev
```

I'm assuming that `upstream` point to official BU repo. The last step could lead to merge conflict that you need to fix manually.

**Comment by marlengit** [comment]
thanks @sickpig I tried those git commands. After the rebase I get a lot of conflicts. I don't know which conflicts to select top or bottom. Is there a way to start with a fresh up to date dev and then merge my PR commits over the top? Or do I have to complete the rebase?

**Comment by sickpig** [comment]
@marlengit 

> Is there a way to start with a fresh up to date dev and then merge my PR commits over the top?

In the same repository of yours, create a local branch which is a clone of current bu/dev and then `cherry-pick` each commits one at a time. 

```sh
git checkout -b new-branch upstream/dev
git cherry-pick <shaid-commit1>
git cherry-pick <shaid-commit2>
git cherry-pick <shaid-commit3>
git cherry-pick <shaid-commit..>
git cherry-pick <shaid-commitn>
```

**Comment by marlengit** [comment]
I found a really easy way to recreate my branch using the git commands below. I've created a new PR and based on latest BitcoinUnlimited/BitcoinUnlimited/dev in a new origin branch dev_gui_tpl so this one can be closed.

git checkout -b dev_gui_tpl upstream/dev
git merge -Xours <commit 1>
git merge -Xours <commit 2>
git merge -Xours <commit n>

That merged most of my changes perfectly. Then I manually reviewed the files and it was fairly easy to pick out the other changes that were mine since I'm familiar with them.

**Pull request closed without merging**
