### PR TITLE
side-effecting code in 2 asserts, and not releasing socket resources in an error condition

### PR DESCRIPTION
**Pull request by gandrewstone**

### CODE REVIEW

**Comment by ftrader** [comment]
Code changes look good to me.

Two questions:

1. how did you detect the unfreed socket - just by code inspection?
2. how did you test the fix for it?

**Comment by gandrewstone** [comment]
1. via coverity

2. this is hard.

a) first start a socks5 proxy:
ssh -D a.b.c.d:9050

b) now this isn't authenticating so change the if statement just above this fix to force it into auth mode anyway.

c) now go to the ConnectThroughProxy() function and change to bad data:
        //random_auth.username = strprintf("%i", insecure_rand());
        random_auth.password = strprintf("%i", insecure_rand());
        random_auth.username = "sadklhfsdkljfasldkfjaskl;dfjasldkfjaskldfjaslkdjfalsk;dfjal;sdkjfaskl;dfjals;kdjfalsk;djfalskdfjalsk;djflak;sdjfalskdjflaskdjflak;sdjfaskl;djflak;sdjfl;askdjfasl;kdfjaskl;djfalsk;dfjl;askdjfl;askdfjaskldjfal;skdjfaskl;djfakl;sdjfal;skdjfalskdjflask;djfklasdjflaksdjfaklsdjfklasdjflasdfasdfasd";

d) now build and run like this:
run -debug=proxy -proxy=127.0.0.1:9050

you will see never-ending output like this:
ERROR: Proxy username or password too long

Not a perfect soln, we should probably quit, but the username/pw CAN'T be bad in the code today because it is a stringified randomly generated integer.

e) watch the leak:
use lsof -p `pidof bitcoind` both with the fix and without to see the sockets being leaked.
if you have the bug, you'll see lots of:
"bitcoind 26351 uname  404u     IPv4             914451      0t0      TCP localhost:48118->localhost:9050 (ESTABLISHED)"

**Review by ptschip — APPROVED** [review]
That always bugged me that they put the view.flush() inside the assert...thanks for that one...as for the socket issue, it looks appropriate...need to close that socket or we'll leak.

**Comment by ptschip** [comment]
is this a backport?  it looks like it's for the dev branch but the indicator on the PR says backport....

**Comment by sickpig** [comment]
You are right the label is confusing, in reality that label means "need
backport". I wonder if we could change so to avoid ambiguity.

On 27 Apr 2017 2:28 p.m., "Peter Tschipper" <notifications@github.com>
wrote:

is this a backport? it looks like it's for the dev branch but the indicator
on the PR says backport....

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/BitcoinUnlimited/BitcoinUnlimited/pull/471#issuecomment-297699148>,
or mute the thread

**Comment by gandrewstone** [comment]
Its on "dev" want to port to "release".  I set the "backport" label to note that I want to put this on both branches.  It looks to me like this PR got 2 signoffs.  If not, please be more clear next time.

**Pull request merged**
