### PR TITLE
Use random hash in graphene tests. Fix for #1206.

### PR DESCRIPTION
**Pull request by ptschip**

### CODE REVIEW

**Comment by bissias** [comment]
I can't quite tell, is GetRandHash() deterministic? Or is it delivering different hashes every time the unit test is run? If it's the latter, then I think there is potential for intermittent failures due to the IBLT decode failure probability.

Looking through the code I think GetRandHash() ultimately calling [rand_bytes](https://linux.die.net/man/3/rand_bytes), which I don't think takes a seed?

**Comment by ptschip** [comment]
just pushed up a fix to make the hashes deterministic but realised the cheaphash will always be 0...i have to reverse the order of the padding and make the 0's trailing.

**Comment by ptschip** [comment]
never mind, it was correct.

**Comment by bissias** [comment]
Nice, it looks good to me.

**Pull request merged**
