### PR TITLE
Fix for a small memory leak in OS X code that handles launch at startup enable/disable

### PR DESCRIPTION
**Pull request by cculianu**
I noticed this when perusing the OS X specific parts of Bitcoin Unlimited.  The use of *Copy* and *Create* calls in the Foundation/Cocoa/Apple APIs always means the caller owns the returned object/reference and it must be released by the caller.

The code in question did not do this.

This pull request fixes this (tiny) memory leak by properly releasing objects when we are done with them.

Please consider merging this into the main fork of BitcoinUnlimited! 👍

### CODE REVIEW

**Comment by cculianu** [comment]
Note that the failed checks have nothing to do with this pull request.

I looked at the fail log and particular test cases on Linux failed.

This is not related to this change which is #ifdef'd to only compile on Mac, and happened to compile fine in the checks listed above if you visit the 'Details' link.

**Comment by ptschip** [comment]
@cculianu try rebasing on the new dev..there was a problem in one of the tests causing intermittent failures.

**Comment by cculianu** [comment]
I'm closing this pull request and I just reopened another one that rebased off of dev.  Thanks for the tip!  Sorry, I'm new to contributing to BitcoinUnlimimted!

**Comment by sickpig** [comment]
@cculianu thanks to you for contributing!
(you should have just rebased your branch and make forced push, no need to close a PR and create a new one.)

**Comment by cculianu** [comment]
Ah.  I see.

I have been developing software for 18 years now.  I use Git all the time.  I'm a nub when it comes to github though, admittedly.  I didn't know how to do that on Github so I just closed and reopened... :/

**Pull request closed without merging**
