### PR TITLE
ensure that mined block size cannot be set > excessive block size

### PR DESCRIPTION
**Pull request by gandrewstone**

### CODE REVIEW

**Comment by gandrewstone** [comment]
This PR does not include a GUI error message if invalid values are entered, although those values will not be accepted.  I want to cherry-pick this into release, and I feel that adding a visual error message is too much change for too little value.  Miners are likely not using the GUI, and there is not machinery to display an error message in the unlimited dialog box, so quite a few changes must be made.

I will add the GUI error message in a subsequent PR.

**Review by ptschip — APPROVED** [review]

**Comment by ptschip** [comment]
@gandrewstone i finished my testing and it looks good...the ui message we don't need right now, the functionality works as it should and like you said the miners are not using the UI most likely anyway.  And there is a log message entry when the event is triggered so I think we should be fine.

**Comment by gmaxwell** [comment]
Is this what caused 000000000000000001a6468d5ae92e40b1177f05d9b66d23fc9f8215690aa820 a day ago?

**Comment by gandrewstone** [comment]
No one reported any issues.  We have already prevented misconfiguration in a few RPC calls and so are extending that prevention to every way MG and EB can be changed.  Block explorers and my nodes are not showing your hash so I can't learn much about it, however, typically if a miner's MG is > its EB the miner won't accept or relay his own block so the block would never hit the network.

**Comment by sickpig** [comment]
need to be backported

**Pull request merged**
