### PR TITLE
Devpool work: express amounts in satoshis in RPC commands

### PR DESCRIPTION
**Pull request by goodvdh**
Added "satoshi" field to JSON transaction data. 
The code  will be added in other relevant places once it is accepted.

Requested in:
Devpool work: express amounts in satoshis in RPC commands
https://bitco.in/forum/threads/devpool-work-express-amounts-in-satoshis-in-rpc-commands.8110/

### CODE REVIEW

**Comment by sickpig** [comment]
In general I'm ok with the with the change with 3 provisos:
1) we need to be sure to break some API for any services using the RPC (don't think so, since JSON is parse-able)
2) Don't we have to do this for all the RPC that have an amount field? 
3) It would be better to add the unit test for the change(s).

**Comment by gandrewstone** [comment]
1. should be fine as you said due to json... this won't be the first time fields have been added.
2. yes, @goodvdh, can you do listsinceblock and listunspent next since there are specific requests for those, and then search the code base for "amount" to find the other RPC calls that have an amount.  Commit additional changes to this PR.
3. I agree, we should be able to do a pretty simple test that compares the decimal and integer quantities.

**Comment by lonoami** [comment]
in re 3: Is it obvious where to add the tests? Or, better, lmk where.

**Comment by gandrewstone** [comment]
these RPC commands are used and tested in the python files located in "qa/rpc-tests".  grep thru these for the command you want to test.  In some cases the command will be used often to test other stuff.  Just find one place where you can add a quick check that the values match.

**Comment by lonoami** [comment]
All places in the code that has "amounts" now also has "satoshis".

**Pull request merged**
