### PR TITLE
CPFP

### PR DESCRIPTION
**Pull request by ptschip**

### CODE REVIEW

**Comment by ptschip** [comment]
https://github.com/ptschip/BitcoinUnlimited/pull/6

**Comment by gandrewstone** [comment]
Reviewed on linked branch

**Comment by ptschip** [comment]
The version of CPFP used in Core was first ported over to BU and then the new CPFP mining algorithm was applied on top.  Tests were run against both the BU(Core) patch and then against the BU CPFP new mining algorithm.  (See chart below for the graphical results)

These tests reflect a random and varied mix of mempool packages.  There will be typically many packages with varying fees scattered throughout the unconfirmed chain. This represents then represents the most challenging long chains I could find to mine with.  The Timing data represents the total time to mine block from 5K in size to 1Mb in size, increasing the value by 5Kb on each iteration.  This gives us then 200 blocks mined.  (The test can be found in miner_tests.cpp and can be run by uncommenting    the test at the bottom called PerformanceTest_PackageSelection(chainparams, scriptPubKey, txFirst);).

Clearly the results show an enormous performance improvement. 
This is accomplished by considering a group of ancestors as a single transaction. We can call these
transactions, Ancestor Grouped Transactions (AGT). This approach to grouping allows us to process
packages orders of magnitude faster than other methods of package mining since we no longer have
to continuously update the descendant state as we mine part of an unconfirmed chain.

There is a theoretical flaw in this approach which could happen when a block is almost full. We
could for instance end up including a lower fee transaction as part of an ancestor group when
in fact it would be better, in terms of fees, to include some other single transaction. This
would result in slightly less fees (perhaps a few hundred satoshis) rewarded to the miner. However,
this situation is not likely to be seen for two reasons. One, long unconfirmed chains are typically
having transactions with all the same fees and Two, the typical child pays for parent scenario has only
two transactions with the child having the higher fee. And neither of these two types of packages could cause any loss of fees with this mining algorithm, when the block is nearly full.

Results were as follows:
Chain   Length | CPFP (Core) | CPFP (BU)
500 | 137 | 0.92
1000 | 326 | 1.16
1500 | 566 | 1.28
2000 | 1102 | 1.43



image

**Comment by JenniferBrooks20132017LSTSEMDAJJPBN** [comment]
HI my account was hacked and i was in prison for a while so now i am back whats happing here?

**Pull request merged**
