### PR TITLE
[PORT] Rolling Bloom Filter new implementation. 

### PR DESCRIPTION
**Pull request by sickpig**
This is a port of: 

https://github.com/bitcoin/bitcoin/pull/7113 
https://github.com/bitcoin/bitcoin/pull/7934

### CODE REVIEW

**Comment by ptschip** [comment]
needs rebase

**Comment by ptschip** [comment]
needs rebase

**Comment by sickpig** [comment]
rebased.

@ptschip sorry for beeing late but somehow I miss your first rebase request.

**Comment by sickpig** [comment]
Add a commit to remove shadowing warnings in `bloom.cpp`

**Review by ptschip — APPROVED** [review]
Tested and seems to be good.

**Pull request merged**
