### PR TITLE
Core #9257: [qa] Dump debug logs on travis failures.

### PR DESCRIPTION
**Pull request by sickpig**
0828619 [qa] Dump debug logs on travis failures. (Suhas Daftuar)

### CODE REVIEW

**Comment by sickpig** [comment]
Taking out of wip. 

Failure is related to a `wallet.py` failure, one of that failure that this patch are suppose to help diagnosing. 

This is an example of the info added to the travis log:

```
Assertion failed: [Decimal('32.99906580'), Decimal('5700.99796160'), Decimal('66.99974800')] != [Decimal('32.99906580'), Decimal('5651.99800000'), Decimal('66.99974800')]
  File "/home/travis/build/BitcoinUnlimited/BitcoinUnlimited/qa/rpc-tests/test_framework/test_framework.py", line 184, in main
    self.run_test()
  File "/home/travis/build/BitcoinUnlimited/BitcoinUnlimited/build/../qa/rpc-tests/wallet.py", line 350, in run_test
    assert_equal(balance_nodes, [self.nodes[i].getbalance() for i in range(3)])
  File "/home/travis/build/BitcoinUnlimited/BitcoinUnlimited/qa/rpc-tests/test_framework/util.py", line 612, in assert_equal
    raise AssertionError("%s != %s"%(str(thing1),str(thing2)))
Stopping nodes
Not cleaning up dir /tmp/testl7en645x
From /tmp/testl7en645x/node0/regtest/debug.log :
2017-05-25 08:57:41 LoadExternalBlockFile: Processing out of order child 59518d50138f709653601ec0e4bb436203f853a9d0fc7f13a2da8c411b6d8ac9 of 206ad19f3d13bf14337f6d95218e332499ceeb6fe5fa3bfb9644d0e7837afc90
2017-05-25 08:57:41 Acceptable block: ver:20000000 time:1495702634 size: 192 Tx:1 Sig:1
2017-05-25 08:57:41 UpdateTip: new best=59518d50138f709653601ec0e4bb436203f853a9d0fc7f13a2da8c411b6d8ac9  height=49  log2_work=6.6438562  tx=50  date=2017-05-25 08:57:14 progress=1.000000  cache=0.0MiB(49tx)
2017-05-25 08:57:41 LoadExternalBlockFile: Processing out of order child 1ecd3d2bbe384f521e283c3ce6fe1cdbceb002d77be7578375e251dfef7db5a0 of ...
```

see here for the complete thing: https://travis-ci.org/BitcoinUnlimited/BitcoinUnlimited/jobs/235941904#L2110

**Comment by sickpig** [comment]
kick the failure job 

attached the log for the failure

[log_1766_1.txt](https://github.com/BitcoinUnlimited/BitcoinUnlimited/files/1031479/log_1766_1.txt)

**Comment by gandrewstone** [comment]
This changes the semantics of the run.  With the PR committed, a failed test will leave the directories behind, similar to if you ran nocleanup.  How will this effect the execution of the tests?

There should be no effect since a random directory is chosen each time, unless you run with the args that explicitly specify a test directory.  If we do that, I think that it will cause all subsequent tests to abort during initialization.  

But since specifying a test directory is only done manually, not deleting the record of the problem is probably more valuable to most engineers than losing the failure but continuing.

**Comment by sickpig** [comment]
@gandrewstone didn't think about that. But as you said I wonder if having the datadir preserved after a failure is not better then the current situation. IMHO it improves the status quo. 

If you want to I can reorganize the code such that the current semantic will be preserved.

**Comment by gandrewstone** [comment]
I think its fine too... wanted to give 24hrs for anyone else to weigh in....

**Pull request merged**
