### PR TITLE
Coin freeze and public label GUI features from marlengit

### PR DESCRIPTION
**Pull request by gandrewstone**

### CODE REVIEW

**Comment by sickpig** [comment]
@thezerg wonder if it is possible to reorganize/polish the commits of this PR (via `rebase -i` aka squash)

**Comment by gandrewstone** [comment]
would I lose attribution to marlengit?

**Comment by sickpig** [comment]
@gandrewstone nope. 

@marlengit authorship could be preserved squashing commits into one authored by him. And in any case you can change the authorship (in the unlikely case the reorg of the PR removes all @marlengit commits)

**Comment by ptschip** [comment]
@marlengit @gandrewstone I tested this out...it works!  The only thing I believe we need to fix, perhaps in a followup PR, is that there is nothing preventing a user from trying to create a freeze address using a non P2SH address...if you created one it appears that the address is grayed out just like a normal freeze address but then of course it isn't frozen and the user may think that it's working when in fact it is not.  It would be easy enough to fix by just filtering out any non P2SH address when the coin-freeze selection is checked as well as the "Reuse and existing address" is selected.

**Comment by gandrewstone** [comment]
superceded by #726

**Pull request closed without merging**
