### PR TITLE
Add CHECKDATASIG to script standard flags

### PR DESCRIPTION
**Pull request by sickpig**

### CODE REVIEW

**Review by ptschip — APPROVED** [review]

**Comment by gandrewstone** [comment]
We need to do a validating IBD to ensure that retroactively enabling this opcode does not cause a validation failure for transactions in old blocks.  An old transaction could have placed CDS in unexecuted branches to make them part of sigop counting consensus while still not being executed.

**Comment by sickpig** [comment]
> We need to do a validating IBD to ensure that retroactively enabling this opcode does not cause a validation failure for transactions in old blocks. An old transaction could have placed CDS in unexecuted branches to make them part of sigop counting consensus while still not being executed.

I think I've done it already, but will redo just to be on the safe side

**Comment by sickpig** [comment]
I checked and I did a normal IBD that was successful. A fully validating (`checklevel=4`, `checkpoints=0`) is ongoing.

**Comment by sickpig** [comment]
@gandrewstone fully validated IBD performed correctly.

**Pull request merged**
