### PR TITLE
[layout] Update various icon and splash screen using the new name and logo

### PR DESCRIPTION
**Pull request by sickpig**

### CODE REVIEW

**Comment by sickpig** [comment]
@ptschip fix the formatting of the spalshscreen by moving version string to avoid overlapping with the BCH Unlimited logo.

**Comment by ptschip** [comment]
> @ptschip fix the formatting of the spalshscreen by moving version string to avoid overlapping with the BCH Unlimited logo.

worked, looks great!

**Review by ptschip — APPROVED** [review]

**Comment by ptschip** [comment]
can you consider adding the following change to /qt/splashscreen.cpp to make the status line text more visible.  Basically making the status text white (255,255,255)


static void InitMessage(SplashScreen *splash, const std::string &message)
{
    QMetaObject::invokeMethod(splash, "showMessage", Qt::QueuedConnection,
        Q_ARG(QString, QString::fromStdString(message)), Q_ARG(int, Qt::AlignBottom | Qt::AlignHCenter),
        Q_ARG(QColor, QColor(255, 255, 255)));
}

**Comment by sickpig** [comment]
@ptschip will do first thing tomorrow

**Comment by sickpig** [comment]
@ptschip done. visibility improved, you were right, here you can see a screenshot of the splash screen:

sc

**Review by ptschip — APPROVED** [review]

**Pull request merged**
