### PR TITLE
Parallel Validation

### PR DESCRIPTION
**Pull request by ptschip**
opening PR on the dev branch

### CODE REVIEW

**Comment by ptschip** [comment]
@gandrewstone taking this out of WIP...I finally fixed the last problem I was having which was showing up on win32...

**Comment by sickpig** [comment]
@gandrewstone @ptschip I wonder if you could add the consensus label to this PR

**Comment by sickpig** [comment]
travis fails here: https://travis-ci.org/BitcoinUnlimited/BitcoinUnlimited/jobs/204568706#L1530

I've tried to reproduce on my local dev machine and I wasn't able to.

@gandrewstone / @AndrewClifford  would you mind restart Travis job 853.6 just to be sure that it is not a casual failure. (click on the "Restart job" button on the upper right corner)

**Comment by ptschip** [comment]
looks like a problem in the comptool...i was able to recreate but is
very intermittent...seems the first time around the bestblockhash
returns None sometimes which causes the python script to fail.  i'm
looking at it.

**Comment by sickpig** [comment]
@ptschip I've tried 4 times in a raw, test passed all the times successfully.

**Comment by ptschip** [comment]
try 20...it's very intermittent...you can just run the very first python
test..bip68-.... if it doesn't happen on the first block it won't...just
keep killing and running ,wait for first block, kill test, run again,
etc...until it happens.

**Comment by ptschip** [comment]
i think it's a timing issue with the mininode when it triggers on a
header..bascically the first iteration the header is None..but we
receive the block and update the blockchain,  but before the header can
update the mininode...anway, still looking at it.

**Comment by gandrewstone** [comment]
It is possible to use a CNode::thinBlock object after its been freed, because CThinBlock::process calls PV.HandleBlockMessage(pfrom, strCommand, pfrom->thinBlock, GetInv()); (line 120), and the thinBlock is passed by reference.  PV.Handle... then creates a separate thread.   But during the execution of this block processing thread, what if the CNode disconnects?

You can prevent CNode cleanup-upon-disconnect by calling CNode::AddRef().  Then at the end of the processing thread, call CNode::Release() to allow the CNode to be cleaned up.

**Comment by ptschip** [comment]
you're right, i'll add that.

**Comment by ptschip** [comment]
@gandrewstone I added and released the ref at the beginning and end of HandlBlockMessageThread()

**Comment by gandrewstone** [comment]
PR issued to solve the bad coinbase height issue...

**Pull request merged**
