### PR TITLE
Redo of PR #190 via git cherry-pick

### PR DESCRIPTION
**Pull request by sickpig**
No actual changes to the code just a redo of #190 in such a way to preserve authorship.

### CODE REVIEW

**Comment by deadalnix** [comment]
29 commits including merges for that ?

The history is a complete spaghetti monster already, I'm not sure this is beneficial. This kind of things make exploring history completely unreasonably hard. Just attribute work in the commit message and be done.

**Comment by sickpig** [comment]
This is what I did in the original PR but It was not enough. So I decided
to backport it via git cherry-pick. I let @gandrewstone decide if to merge
or not.

**Comment by deadalnix** [comment]
Considering I'm now backporting code from core, I can attest first hand of how much of a pain in the ass this is. Somehow people got convinced that it was a good idea, because decentralized source control and yada yada, but it is not.

**Comment by sickpig** [comment]
@gandrewstone 

travis build fails on both linux conf due to this error: 

```
The command "if [ "$RUN_TESTS" = "true" ]; then make $MAKEJOBS check VERBOSE=1; fi" exited with 0.0.27s
$ if [ "$RUN_TESTS" = "true" ]; then qa/pull-tester/rpc-tests.py --coverage; fi
ERROR: "import zmq" failed. Set ENABLE_ZMQ=0 or to run zmq tests, see dependency info in /qa/README.md.
Traceback (most recent call last):
  File "qa/pull-tester/rpc-tests.py", line 158, in <module> 
    raise e
  File "qa/pull-tester/rpc-tests.py", line 154, in <module>
    import zmq
ImportError: No module named 'zmq'
```

this should mean that package python-zmq is not installed when in fact it should be since it is pecified in the travis conf file.

Another strange thing is that same build did not fail on the PR build. 

Maybe is running with python3 now that you have merge the Jan17merge branch?

**Comment by ptschip** [comment]
Just to throw my own two cents in , I'm all for giving proper
attribution but if the code bases diverge too much then I think we can
obvioulsy end up going to extremes in our cherry picking efforts just
for the sake of attribution.   Can't we rather just do a manual cherry
pick and then change with --amend "Author" so that if anybody want's to
search in git on who did the work, then it will show up correctly?

**Comment by sickpig** [comment]
my fault I thought it was this merge that failed instead was the rebase Jan 17 merge. 

one problem is that we need to update pythin3-zmq, cause otherwise the python suite will fail 

I'll look into it in one hour

**Comment by sickpig** [comment]
@ptschip what you described is more or less what I did  with #190.

Just have a look at the comments posted on the PR thread
to get an idea of the can of worms I've opened.

That said I think this is just a matter of finding the right compromise.

In my opinion we are still able to more or less include
codes from Core with cherry pick without "much" effort.

Until this remains valid I think cherry picking is the right way
to go.

As soon as for each attempted cherry you'll start fixing
tons of conflicts, remove path from the commit etc etc
then it's time to move to the "manual" way.

**Comment by deadalnix** [comment]
When there are more commits than line changed, you know you missed "the right compromise" by quite a bit.

**Comment by sickpig** [comment]
again it wasn't me who requested to redo #190. please just read the
original PR thread.

that said what I think is important is not the number of cherry picked
commits but how every single cherry-pick applies smoothly or not.

But maybe it's me.

**Pull request merged**
