### PR TITLE
Updating Chinese translations

### PR DESCRIPTION
**Pull request by kFTY**
The translation “比特币核心”（Bitcoin Core in Chinese） are now all changed to
“比特币无限” (Bitcoin Unlimited in Chinese). The translation of “leave that many cores free” was wrong about the word "free", its translation now changed to "预留" （leave the space free）instead of previously"自由"(freedom)

### CODE REVIEW

**Comment by ptschip** [comment]
@kFTY That's great but can you resubmit against the "dev" branch, thanks.  We use only "dev" for new things and "release" for current mainnet.  We don't use master (i think @gandrewstone  was going to remove master but he's got the flu and probably forgot).

@digitsu are you able to review this or anybody else that can read/write Chinese?

**Comment by ptschip** [comment]
@kFTY   in case you don't know you don't have to resubmit the PR, just click on Edit and then change your base branch to dev..thanks.

**Comment by ptschip** [comment]
@kFTY  Also could you change the title of the PR to be something like "updating Chinese transalations" or something along those lines...thanks again!

**Comment by ptschip** [comment]
@kFTY  you'll need to rebase your PR onto dev for this to go through Travis...

**Comment by kFTY** [comment]
@ptschip Yes, I have changed the base branch to BitcoinUnlimited:dev already

**Comment by kFTY** [comment]
@ptschip OK, I think now I got your point. I make it again for dev branch.

**Pull request closed without merging**
