### PR TITLE
Backport of kyuupichan's xthin-checks branch to 'release'

### PR DESCRIPTION
**Pull request by ftrader**
Original PR for 'dev': PR https://github.com/BitcoinUnlimited/BitcoinUnlimited/pull/540

FIXME's not yet resolved - more analysis and reviews needed

### CODE REVIEW

**Comment by zander** [comment]
Please be aware that this does not fix the attack vector.

A fully properly mined block can still be gigabytes in size and you would not catch it with this change.

**Comment by kyuupichan** [comment]
It is intended to stop even looking at old blocks or blocks built on old blocks.  It means you have to burn 12.5 BTC and have a lot of hash power to attempt an attack.

ptschip has a separate PR to solve the memory consumption issue.  But we should not be attempting to build a block at all in a resource-consuming way until it has passed muster, which is what this PR is about.  That is something Classic needs to fix.

**Comment by zander** [comment]
> That is something Classic needs to fix.

Classic has fixed this already.

**Comment by sickpig** [comment]
@ftrader 

you need to apply latest change made by @kyuupichan on #540

see:

https://github.com/BitcoinUnlimited/BitcoinUnlimited/pull/540/commits/ea94bedc27a8863bf32cd0d61a86b39cb87dcb37

**Review by ftrader — COMMENTED** [review]
Reviewed and ok with the changes

**Pull request merged**
