### PR TITLE
Merge Release 1.4.0.0 into release branch

### PR DESCRIPTION
**Pull request by gandrewstone**

### CODE REVIEW

**Comment by ptschip** [comment]
this keeps on failing, but also wondering why are there two different build processes,  /travis-ci/pr and /travis-ci/push?

**Comment by gandrewstone** [comment]
I don't know why 2 sets.  But the builds are timing out still making progress  (not hung).  I'm about ready to merge this even with travis issues.  I'll do a local compare to make sure files are identical to dev branch

**Comment by ptschip** [comment]
@gandrewstone also wondering why you don't just merge dev into release?

**Comment by sickpig** [comment]
> @gandrewstone also wondering why you don't just merge dev into release?

I agree. 

Seems like you merged `dev` in your local `release` and then now you are try to merge your local `release` branch into BU `dev` branch.

**Comment by gandrewstone** [comment]
I merged dev into release in my clone and then opened this pr to merge my clones release into release

EDIT:
I verified that after this PR, release will be identical to dev by doing a file comparison locally.  I am going to merge now, even though some builds keep timing out (for posterity: we are having consistent travis timeout issues beyond just this PR)

**Pull request merged**
