### PR TITLE
C++11 build/runtime fixes

### PR DESCRIPTION
**Pull request by deadalnix**
Backport from core.

### CODE REVIEW

**Comment by gandrewstone** [comment]
I have merged these out to the deadalnix-cpp11 branch since there were changes I made for ARM and MAC on that branch.  Please help me test it there before merging.

**Comment by deadalnix** [comment]
Please merge this into the main branch if you have no concern with the code. Having branch to stabilize feature doesn't work unless the dev branch grind almost to an halt. If it moves fast, you end up with a lot of work backporting or rebasing from it, and never converge toward something stable. Which tends to cause the dev in the main branch to grind to an halt, and the loop is closed. You also get other perverse incentive, such as the change merged are large rather than focused and incremental, which makes reverting them very hard, which decrease the amount of risk you can take and once again, force to slow things down.

Anyway without this, nothings compile with gcc6 onward.

**Comment by deadalnix** [comment]
Rebased on top of #248 . This fixes the conflict with f4301e3933153a18fcd6e8022bf2e6f3d7386a3b . Checked with @sickpig that it's all good.

**Comment by gandrewstone** [comment]
deadalnix-cpp11 was merged into 0.12.1bu... so closing this PR...

**Pull request closed without merging**
