### PR TITLE
'Fix' leveldb build when building out of tree

### PR DESCRIPTION
**Pull request by deadalnix**
That's pretty much it, this allow to build out of tree.

### CODE REVIEW

**Comment by gandrewstone** [comment]
Some questions so I understand what's going on here:

what do you mean "building out of tree"?  Do you mean building leveldb out of the Bitcoin source tree?  Why are you building out of tree and when to other people need to do it?    

How does your fix solve the problem?  To me it looks like it is forcing the build to be IN the tree...
also is the "if EMBEDDED_LEVELDB" flag relevant to what you are trying to build?  I think by "embedded" they mean to build the LEVELDB that is "embedded" in the Bitcoin source.  So if you were building leveldb out of tree, perhaps EMBEDDED_LEVELDB should not be defined?

**Comment by deadalnix** [comment]
I'm talking build BU outside of tree (not mixing the object files with the sources).

I'm building out of tree because that allow to have several build with several build option from the same sources.

**Comment by gandrewstone** [comment]
I don't understand how your fix builds out of tree... it looks to me like it switches things to grab images that were built IN tree.  In theory "builddir" could point to your out-of-tree target directory, so leveldb could be built out of tree given the original code.  But with your changes, doesn't "$(top_srcdir)/src" mean that leveldb will be grabbed from IN the tree so it therefore must be built in the source tree?

I really appreciate that you are working on BU, but please understand that if I ask about 7 questions and you answer only one of them then your PR will get delayed as I work thru other PRs and then ask the same questions all over again.  I'd really appreciate it if you would go through all of my questions in this and the prior comment and answer them.  If you don't, this PR will have to wait until I have time to attempt to trigger the issue by repeating your work, which could be hard with no details.

**Comment by deadalnix** [comment]
It doesn't build leveldb out of tree, this aparently cannot be done without changing leveldb build. But it builds everything else out of tree.

**Comment by deadalnix** [comment]
Ping ?

**Comment by gandrewstone** [comment]
somehow this PR is now showing 766 files to be changed.  I remember that it was just 2 or 3 lines... so something has gone wrong.  If you could reissue the PR, and in a comment tell me how you trigger an out-of-tree build (probably your ./configure line), I'll try to reproduce.  

We will probably need to also build leveldb out-of-tree, since leaving some parts in-tree is dangerous -- things like crossbuilds or different compilation flags won't work for the portion that is in tree.

**Comment by deadalnix** [comment]
I think this is because I sent my PR against master. Should I aim at master or 0.12.1bu ?

Also, yes for moving leveldb out of tree, but one has to start somewhere. Leveldb use its own build so I need to understand it first.

**Comment by sickpig** [comment]
0.12.1bu is the one you have to base the PR against

**Comment by deadalnix** [comment]
Here you go.

And travis <3

**Comment by deadalnix** [comment]
Ok travis seems to be flaky for some arch, but this patch looks good.

**Comment by ptschip** [comment]
travis isn't working yet... but it looks like @sickpig has started to do
some work on getting it running .

**Comment by deadalnix** [comment]
Ping ?

**Comment by gandrewstone** [comment]
what configure, etc commands are you running to start an out-of-source-tree build?

**Comment by deadalnix** [comment]
mkdir build
../configure
make

**Comment by deadalnix** [comment]
configure and make, from the folder I want to build in.

**Comment by sickpig** [comment]
@thezerg

let say that for whatever reason you want to build BU binaries and all it's dependencies in a subdir of the source tree, e.g. `buildme`,  you should be able to something like: 

```
cd /path/to/BU/cloned/repo
mkdir buildme
cd buildme
../configure --with-fancy-opition
make
```

currently this is not possible due to the fact that LevelDB will fail to compile, cause the autoconf/tools machinery want the LevelDB source code to be located in a subdir of the current directory named `leveldb`

this PR fix this problem and remove such assumptions. 

On a side note this will be useful to have also for the Travis tweaks I'm testing.

**Comment by deadalnix** [comment]
Ping ?

**Comment by deadalnix** [comment]
So what is wrong here ? This is a 2 line fix and it has been open for 3 weeks and there is still no actionable item in the comments. What is going on ?

**Comment by sickpig** [comment]
@gandrewstone fwiw I'm in favor of merging this PR. That said in the contest of my travis work I'm preparing a more comprehensive refactor of the build machinery to make it out-of-tree "compliant" (see https://github.com/sickpig/BitcoinUnlimited/commits/test/travis-ci)

**Comment by gandrewstone** [comment]
@deadalnix I'm sorry for the delay.  To explain the delay a bit, I could never get a clear answer on how this PR does an out-of-tree build, by grabbing leveldb from inside the tree.  So I had to try it myself.

Now I understand that the PR allows an out-of-tree build of everything except leveldb.  I am not happy with that solution because the purpose of an out-of-tree build is to build for different architectures or with different flags.  But by leaving part of the build in-tree, I imagine that the out-of-tree build will either fail (crossbuilds) or silently succeed but with the wrong flags for leveldb.

I am sorry that I did not update the PR with this info.  sickpig had told me that he would have a full-fledged solution, so I let this drop off of my to do list.

Would it be possible to enhance the PR to build fully out-of-tree?

**Comment by deadalnix** [comment]
As far as I understand the build system, leveldb has its own build and bitcoin's build system call into it. It doesn't appear that leveldb's build system can build out of tree itself. Getting this to work properly with leveldb out of tree would require some significant refactoring of the build.

I would also like to have it work, but we are looking at changing 2 lines vs changing how leveldb is built.

**Comment by deadalnix** [comment]
Ping ?

**Comment by gandrewstone** [comment]
I had a hard time believing that LevelDB, a mature FOSS DB doesn't have an out-of-tree build.

I spent 10 minutes and found that Core has already done all the work: "https://github.com/bitcoin/bitcoin/pull/7911/files".

Since you raised the issue, I would really appreciate it if you would do this kind of investigation rather than spending your time herding me into doing it.  Herding me is why this issue is moving so slowly.

**Comment by deadalnix** [comment]
Good find. Let me adapt this. However, please note that core redid the leveldb build, which is consistent with my findings: the build system that comes with leveldb doesn't support out of tree build.

**Comment by sickpig** [comment]
@deadalnix I've done the job already, see: https://github.com/sickpig/BitcoinUnlimited/tree/test/travis-ci
I'm currently integrate such changes in a branch where I've merged  0.12 core onto latest BU 0.12.1bu just to be ready for the next release.

**Comment by deadalnix** [comment]
Awesome, should I close this pr, then ?

**Comment by sickpig** [comment]
Just leave it open as a reminder, as soon as I'm done with my test I'll ping you so that you could close it.

**Comment by deadalnix** [comment]
Alright, is there anything I can do to help ?

**Comment by sickpig** [comment]
@deadalnix sure :smile: 
As soon as the branch I'm setting up (0.12 core merge + travis enhancements + out-of-tree) will be ready you could review it, looking for bad merging call or just plain bugs. 
I think it will be ready tomorrow (central europe time).

**Comment by deadalnix** [comment]
@sickpig id you make any progress with this ? If not, maybe we should reconsider merging this. If yes, I'll close this.

**Comment by sickpig** [comment]
@deadalnix leveldb out-of-tree builds has been merged a week or so ago. Just give it a try and let me know if it works or not

**Comment by deadalnix** [comment]
Funny you mention it, I'm building right now using it to see how it goes :)

**Comment by deadalnix** [comment]
i got other problem, but leveldb is not one of them anymore. Closing.

**Pull request closed without merging**
