### PR TITLE
Dsp from flowee

### PR DESCRIPTION
**Pull request by gandrewstone**

### CODE REVIEW

**Comment by Justaphf** [comment]
Have been running this on mainnet over the last couple weeks on a Windows 64-bit build (built on Windows 10 using mingw) and periodically the node crashes with an Access Violation `ExceptionCode: c0000005 (Access violation) Attempt to read from address ffffffffffffffff`.  This usually occurs within less than 2 days uptime.  I haven't really been testing this feature, just wanted to give it a run and see what the level of double-spends detected on mainnet are.  However, given the frequent crashes I wanted to share this bug report.

My builds have been this branch rebased on latest `dev` branch, Windows 64-bit, QT client.  No other changes included from me beyond rebasing and modifying the Windows build configuration script to my local machine (`./build-aux/mingw/SET_ENV_VARS.bat`).  My last build was rebased on a70bb86, though I've had 4 or 5 other builds rebased at earlier points on `dev` too, all showing the same behavior.

I was running with the `dsproof` logging option turned on, however, there is nothing of interest in the log file related to the crash that I could see.  The log just stops when the crash occurs.  The first few times it crashed I didn't have my system configured to capture crash dumps, but the last 5 I did.  The First couple of crash dumps I have also were against stripped versions of the executable, the last few though I had built skipping the strip option.  All of them show a stack trace for the crash similar to below, pulled from the dump via Windbg.exe (64-bit).

```
STACK_TEXT:  
00000000`3551e960 00000000`00280c1c : 00000000`000014f8 00000000`00000000 00000000`3551eb78 00000000`00000001 : bitcoin_qt+0x212feb
00000000`3551ea90 00000000`002824cc : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : bitcoin_qt+0x1a0c1c
00000000`3551f500 00000000`0136a9df : 00000000`00000000 00000000`00000000 00006994`499f1684 00000000`29d2ecf8 : bitcoin_qt+0x1a24cc
00000000`3551fde0 00000000`00faf3a4 : 00000000`29d2ecf8 00000000`00000000 00000000`00000000 00007ffe`c887aadb : bitcoin_qt!secp256k1_schnorr_sign+0x3fb67f
00000000`3551fe20 00007ffe`c887b04a : 00000000`29d2ecc0 00000000`00000000 00000000`29d37d70 00000000`00000000 : bitcoin_qt!secp256k1_schnorr_sign+0x40044
00000000`3551fe70 00007ffe`c887b11c : 00007ffe`c88d06d0 00000000`29d37d70 00000000`00000000 00000000`00000000 : msvcrt!_callthreadstartex+0x1e
00000000`3551fea0 00007ffe`c6db7bd4 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : msvcrt!_threadstartex+0x7c
00000000`3551fed0 00007ffe`c8baced1 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : kernel32!BaseThreadInitThunk+0x14
00000000`3551ff00 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x21
```
This issue only happens with this DSP feature included.  Without I can generally run my node uninterrupted for weeks straight.

NOTE: Not sure if it's relevant, but I also have `ENABLE_TESTS` turned on in my build configuration.

**Comment by Justaphf** [comment]
I think I may have found the cause for the crash.  I made a change that replaces direct usage of `CTransaction` in the DSP code to instead use `CTransactionRef`.  As part of this I modified a couple locations to use `MakeTransactionRef()` and a couple of other locations to use `CTxMemPoolEntry.GetSharedTx()` instead of `CTxMemPoolEntry.GetTx()`.  This seems to have corrected the crash for me.  At least my node has been up for more than 2 days now without crashing.  Granted the volume of DS detected seems to be lower than when I was testing earlier, so that may be a factor.

Based on the modifications above seeming to correct the crash, I investigated a little deeper into the code and the places I needed to change were all related to use of the `CInPoint` class.  Based on this I'm wondering if the proper fix may actually be to convert the `CInPoint.ptx` member from being a `CTransaction` pointer to a `CTransactionRef` instead in order to use the smart pointer.  However, I'm not familiar enough with the code base to be sure about that or when/why a specific location should use `CTransaction` versus `CTransactionRef`.

I'm going to let my node run through the weekend and see if I hit any crashes.  If not I can submit a PR against this PR with the current set of changes I made, unless someone more knowledgeable can confirm if modifying the `CInPoint` class is the correct way to go.

**Comment by ptschip** [comment]
> I think I may have found the cause for the crash. I made a change that replaces direct usage of `CTransaction` in the DSP code to instead use `CTransactionRef`. As part of this I modified a couple locations to use `MakeTransactionRef()` and a couple of other locations to use `CTxMemPoolEntry.GetSharedTx()` instead of `CTxMemPoolEntry.GetTx()`. This seems to have corrected the crash for me. At least my node has been up for more than 2 days now without crashing. Granted the volume of DS detected seems to be lower than when I was testing earlier, so that may be a factor.
> 
> Based on the modifications above seeming to correct the crash, I investigated a little deeper into the code and the places I needed to change were all related to use of the `CInPoint` class. Based on this I'm wondering if the proper fix may actually be to convert the `CInPoint.ptx` member from being a `CTransaction` pointer to a `CTransactionRef` instead in order to use the smart pointer. However, I'm not familiar enough with the code base to be sure about that or when/why a specific location should use `CTransaction` versus `CTransactionRef`.
> 
> I'm going to let my node run through the weekend and see if I hit any crashes. If not I can submit a PR against this PR with the current set of changes I made, unless someone more knowledgeable can confirm if modifying the `CInPoint` class is the correct way to go.

That's a good observation. It think using the transaction ref might be the better way to go although I haven't looked at the DSP code yet. In general though we've been moving toward using tx refs where ever we can.

**Comment by Justaphf** [comment]
Ultimately switching to `CTransactionRef` did not fix the issue, the crash still happens intermittently.  I saw that Tom pushed some additional commits to his original PR branch so I've incorporated those as well as rebasing on latest `dev` branch and will see if the error recurs with those fixes.  Sometimes it happens within 24 hours of restarting and sometimes my node will be up for weeks before it recurs.

**Pull request closed without merging**
