### PR TITLE
Remove unused function in cashlib

### PR DESCRIPTION
**Pull request by sickpig**

### CODE REVIEW

**Comment by sickpig** [comment]
it turns out that is necessary to get the binaries built on win. The failure happens at link time.

```
.libs/libbitcoincash_la-random.o:random.cpp:(.text+0x6d0): undefined reference to `LogPrintStr(std::string const&)'
.libs/libbitcoincash_la-random.o:random.cpp:(.text+0x851): undefined reference to `LogPrintStr(std::string const&)'
.libs/libbitcoincash_la-random.o:random.cpp:(.text+0xa2d): undefined reference to `LogPrintStr(std::string const&)'
/usr/bin/i686-w64-mingw32-ld: .libs/libbitcoincash_la-random.o: bad reloc address 0x27c in section `.rdata'
collect2: error: ld returned 1 exit status
.....
```

**Comment by gandrewstone** [comment]
cashlib included functions from the rest of the code that call logging.  If we don't get an undefined symbol then I guess that I removed the functions that called logging from cashlib.  

However, chances are extremely good that new functions will be added, or that someday someone will add a log to one of the functions that cashlib uses.  In the former case, the person developing cashlib will have to do the same debugging I had to do.  In the latter case, the programmer will suddenly get a regession test failure in code that seems unrelated to his change.  

We should keep this function in cashlib to stop these problems from happening to our future selves.


EDIT: yes cashlib gets undefined ref during build.

Making check in src
make[1]: Entering directory `/home/travis/build/BitcoinUnlimited/BitcoinUnlimited/build/src'
make[2]: Entering directory `/home/travis/build/BitcoinUnlimited/BitcoinUnlimited/build/src'
  CXXLD    libbitcoincash.la
.libs/libbitcoincash_la-random.o:random.cpp:(.text+0x6d0): undefined reference to `LogPrintStr(std::string const&)'
.libs/libbitcoincash_la-random.o:random.cpp:(.text+0x851): undefined reference to `LogPrintStr(std::string const&)'
.libs/libbitcoincash_la-random.o:random.cpp:(.text+0xa2d): undefined reference to `LogPrintStr(std::string const&)'
/usr/bin/i686-w64-mingw32-ld: .libs/libbitcoincash_la-random.o: bad reloc address 0x27c in section `.rdata'
collect2: error: ld returned 1 exit status
make[2]: *** [libbitcoincash.la] Error 1
mak

**Comment by sickpig** [comment]
what's strange is that the linker problem happens only for win32/64. wonder why.

**Comment by sickpig** [comment]
@gandrewstone the error message you add to your comment is the exact same err msgs I reportehttps://github.com/BitcoinUnlimited/BitcoinUnlimited/pull/1152#issuecomment-398377002d here https://github.com/BitcoinUnlimited/BitcoinUnlimited/pull/1152#issuecomment-398377002

IMHO the error happens at linker time rather during build. What I'm trying to understand is why the linker error is raised only on win platforms and not for linux/osx, even thou the symbol is marked as undefined also on linux:

```
$> cd src/.libs/
$> nm libbitcoincash_la-random.o | grep LogPrintStr 
      U _Z11LogPrintStrRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

**Comment by sickpig** [comment]
found out a a partial reason why we have the prob,e on win32/64. 

in https://github.com/BitcoinUnlimited/BitcoinUnlimited/blob/dev/src/random.cpp#L51 we `ifdef` code in case we run on win platform and in such code we adds to `LOG` calls:

```c++
        LOG(RAND, "%s: %lu bytes\n", __func__, nSize);
        ...
        LOGA("%s: Warning: RegQueryValueExA(HKEY_PERFORMANCE_DATA) 
``` 

and this results in a different set of symbols referring to `Log*`

```
$> nm libbitcoincash_la-random.o | grep Log
0000000000000000 r .rdata$.refptr._ZN7Logging17categoriesEnabledE
0000000000000000 R .refptr._ZN7Logging17categoriesEnabledE
                 U _Z11LogPrintStrRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
                 U _ZN7Logging17categoriesEnabledE
```

@gandrewstone that said do you think that is right for bitcoincash lib to link to code that use `bitcoind` logging facilities?

**Comment by gandrewstone** [comment]
@sickpig yes, the value of the bitcoincash lib is that it reuses stuff from bitcoind.  So it will certainly pull in code that uses various facilities of bitcoind, and some of those facilities will be not applicable in the context of libbitcoincash.  Functions have an interface, but they also have an "underface" (the underlying services used).  We may need to no-op or reimplement some of these underface APIs in the context of libbitcoincash.  For example, the library really should allow a caller to provide a log destination function pointer and our implementation of logging should call that function if its non-null.  That way the application can do whatever it wants with the library's logs.  This is a small project that can be done when and if the library starts being used for more than test.

**Pull request closed without merging**
