### PR TITLE
Documentation for Graphene v2.1, IBLT, and fast Bloom filter

### PR DESCRIPTION
**Pull request by bissias**
This PR updates the Graphene protocol specification to include the details of version 2.1 and also adds separate specifications for the invertible bloom lookup table (IBLT) and fast Bloom filter, two important data structures in the Graphene protocol.

### CODE REVIEW

**Comment by Greg-Griffith** [comment]
@bissias you can add [skip ci] to the commit message to get travis to skip running for that commit for stuff that doesnt need it like doc changes

**Comment by bissias** [comment]
Ah, thanks for the tip @Greg-Griffith. I was wondering about that.

**Comment by deadalnix** [comment]
This specification describes how the code implements graphene rather than grapehene. This is not very useful as a specification, but indeed better than nothing.

There seems to be many design choices that are not motivated. They don't need to be in the spec, but they will have to in some way. For instance, it is left to the sender to figure out what values are proper for the number of hash functions to use for the filter. What kind of gains are we looking at by getting these value free rather than pick them based on some heuristic? It's an important question, because if we are saving 10 bytes by doubling the amount of work to decode, then it is completely the wrong tradeof. In addition, this strategy clearly opens attack vectors that this document completely slip under the rug by simply assuming the recipient will accept filters only "provided that they are reasonably sized" which is not actionable for implementer, but worse, the sender cannot know what the recipient assumes is reasonable.

Value presented as justification do not match with various design choices. For instance buckets count are 32bits, but the largest number I can find in term of transaction count is 10000, which is far bellow. How does things go when size above 60k are reached? Is it better to shard the block or to do one giant grapehene message? If the first one is preferable, then many fields are oversized, and if the second is, then actual data to justify it are necessary.

It is an error to leave to the sender the choice of the siphash seeds. Please adopt compact's block way of agreeing on a seed. It is completely unclear what the siphash nonce is for.

computeOptimized seems to be cruft from previous versions.

Putting version at the end is completely inconsistent with all the existing messages and also a pretty bad idea because that prevent any adaptation of the pre version structure - or at least its size.

The protocol is unnecessarily complex in presence of CTOR.

Bitcoin's bloom filter is notoriously bad. If it where to be reused as this, then there may be an argument to do so for consistency, but that isn't even the case here.

It's not clear what the exchange of messages is supposed to look like from what is there, but it seems like there still isn't a high bandwidth mode. This makes the whole project almost useless at this stage as one round trip is going to be more costly than whatever win we get from compression.

Many of this feedback was provided for version 1 and hasn't changed much.

Stepping back, I'm surprised to find a request for comment now while:
1/ No attempt to discuss the spec has been made prior for month now.
2/ Most of the feedback from the previous iteration has not been addressed.

**Comment by bissias** [comment]
@deadalnix thanks very much for the feedback. Since it was a long post, I'm going to reply in multiple responses.

**Comment by bissias** [comment]
> This specification describes how the code implements graphene rather than grapehene. This is not very useful as a specification, but indeed better than nothing.

I admit that it's probably more apt to describe this as a combination design doc / spec. But my intention was to include enough detail about the protocol and network format for others to implement it from scratch.

**Comment by bissias** [comment]
> There seems to be many design choices that are not motivated. They don't need to be in the spec, but they will have to in some way. For instance, it is left to the sender to figure out what values are proper for the number of hash functions to use for the filter. What kind of gains are we looking at by getting these value free rather than pick them based on some heuristic? It's an important question, because if we are saving 10 bytes by doubling the amount of work to decode, then it is completely the wrong tradeof. 

In general, you're right about design choices. Graphene requires a lot of design decisions to be made. Until now, I've made most of those decisions by consulting with BU devs. But my intention with this spec / design doc is to get the kind of feedback you are providing now.

Regarding the number of hash functions specifically, figure 7 in the [latest graphene paper](https://people.cs.umass.edu/~gbiss/graphene.sigcomm.pdf) shows how the probability of an IBLT decode failure is affected by a fixed number of hash functions. It should be noted that the failures are worse with small blocks. When blocks are large, greater than 1K txs for example, the optimal number of hash functions converges to 4. Note also that the most hash functions [ever used](https://github.com/BitcoinUnlimited/BitcoinUnlimited/blob/release/src/iblt_params.h) is 9. So we shouldn't expect that space-optimizing IBLTs will incur much more than 2x increase in CPU overhead.

> In addition, this strategy clearly opens attack vectors that this document completely slip under the rug by simply assuming the recipient will accept filters only "provided that they are reasonably sized" which is not actionable for implementer, but worse, the sender cannot know what the recipient assumes is reasonable.

I agree with this criticism. "Reasonably sized" is way too vague. I can tell you that right now, the receiver will [fail block deserialization](https://github.com/BitcoinUnlimited/BitcoinUnlimited/blob/68d87c9d637583e8b89218f969caf624a76141cc/src/blockrelay/graphene_set.h#L176) if the sender has created a block assuming more than 10M txs in the mempool. Also, we [cap](https://github.com/BitcoinUnlimited/BitcoinUnlimited/blob/68d87c9d637583e8b89218f969caf624a76141cc/src/blockrelay/graphene.h#L121) the number of transactions in the block during deserialization to `excessiveBlockSize * maxMessageSizeMultiplier / 100`. I can't say that these are the best values; I think it's worth discussing. There are probably other checks that should be performed as well. @awemany is usually has some opinion on these matters.

**Comment by bissias** [comment]
> There seems to be many design choices that are not motivated. They don't need to be in the spec, but they will have to in some way. For instance, it is left to the sender to figure out what values are proper for the number of hash functions to use for the filter. What kind of gains are we looking at by getting these value free rather than pick them based on some heuristic? It's an important question, because if we are saving 10 bytes by doubling the amount of work to decode, then it is completely the wrong tradeof. 

In general, you're right about design choices. Graphene requires a lot of design decisions to be made. Until now, I've made most of those decisions by consulting with BU devs. But my intention with this spec / design doc is to get the kind of feedback you are providing now.

Regarding the number of hash functions specifically, figure 7 in the [latest graphene paper](https://people.cs.umass.edu/~gbiss/graphene.sigcomm.pdf) shows how the probability of an IBLT decode failure is affected by a fixed number of hash functions. It should be noted that the failures are worse with small blocks. When blocks are large, greater than 1K txs for example, the optimal number of hash functions converges to 4. Note also that the most hash functions [ever used](https://github.com/BitcoinUnlimited/BitcoinUnlimited/blob/release/src/iblt_params.h) is 9. So we shouldn't expect that space-optimizing IBLTs will incur much more than 2x increase in CPU overhead.

> In addition, this strategy clearly opens attack vectors that this document completely slip under the rug by simply assuming the recipient will accept filters only "provided that they are reasonably sized" which is not actionable for implementer, but worse, the sender cannot know what the recipient assumes is reasonable.

I agree with this criticism. "Reasonably sized" is way too vague. I can tell you that right now, the receiver will [fail block deserialization](https://github.com/BitcoinUnlimited/BitcoinUnlimited/blob/68d87c9d637583e8b89218f969caf624a76141cc/src/blockrelay/graphene_set.h#L176) if the sender has created a block assuming more than 10M txs in the mempool. Also, we [cap](https://github.com/BitcoinUnlimited/BitcoinUnlimited/blob/68d87c9d637583e8b89218f969caf624a76141cc/src/blockrelay/graphene.h#L121) the number of transactions in the block during deserialization to `excessiveBlockSize * maxMessageSizeMultiplier / 100`. I can't say that these are the best values; I think it's worth discussing. There are probably other checks that should be performed as well. @awemany is usually has some opinion on these matters.

**Comment by bissias** [comment]
> Value presented as justification do not match with various design choices. For instance buckets count are 32bits, but the largest number I can find in term of transaction count is 10000, which is far bellow. How does things go when size above 60k are reached? Is it better to shard the block or to do one giant grapehene message? If the first one is preferable, then many fields are oversized, and if the second is, then actual data to justify it are necessary.

Maybe I'm misunderstanding something here. Are you referring to the count field in `HashTableEntry`? Since it's int32_t it can count up to ~2B txs, right? I admit that's probably overkill, but int16_t only counts up to ~30K, which seems a little too low.

**Comment by bissias** [comment]
> It is an error to leave to the sender the choice of the siphash seeds. Please adopt compact's block way of agreeing on a seed. 

So I actually did copy from the implementation of compact blocks written by @TheBlueMatt for this. Genuinely asking, can you describe the vulnerability associated with allowing the sender to set the sipHash seed? I mean, yes he could potentially set the seed so as to ensure that there exist cheap hash collisions. But if he was intent to disrupt block propagation, he could ensure that the block does not decode in numerous other ways (for example by filling the IBLT with garbage).

> It is completely unclear what the siphash nonce is for.

Agreed. This appears to be cruft. I'll remove it from the spec.

**Comment by bissias** [comment]
> computeOptimized seems to be cruft from previous versions.

Agreed, will remove.

**Comment by bissias** [comment]
> Putting version at the end is completely inconsistent with all the existing messages and also a pretty bad idea because that prevent any adaptation of the pre version structure - or at least its size.

This is an error in the doc. Actually there is no version field in either the CGrapheneBlock or CGrapheneSet objects. I'll fix that. Graphene block version is communicated through xversion bits (or the equivalent protocol-level versioning system). We instantiate objects with the appropriate version given the xversion bits.

**Comment by bissias** [comment]
> The protocol is unnecessarily complex in presence of CTOR.

If CTOR is present, which of course is always the case in BCH, then all that is necessary is to set the `ordered` flag to 0 and leave `encodedRank` empty. But I can see how this is a waste of space if you're only coding for BCH. @gandrewstone do you have an opinion on this? Should we drop these fields?

**Comment by bissias** [comment]
> Bitcoin's bloom filter is notoriously bad. If it where to be reused as this, then there may be an argument to do so for consistency, but that isn't even the case here.

Totally agreed. I have been bitten multiple times by surprise behavior in CBloomFilter. With that being said, in this spec we're providing the option (for the implementer) to choose between CBloomFilter and CVariableFastFilter, the latter of which is much slimmer and faster. In BU we support both, but that's only for legacy reasons.

**Comment by bissias** [comment]
> It's not clear what the exchange of messages is supposed to look like from what is there, but it seems like there still isn't a high bandwidth mode. This makes the whole project almost useless at this stage as one round trip is going to be more costly than whatever win we get from compression.

That is correct, we do not currently support high bandwidth mode (aka "expedited mode" in BU). Graphene is a little different from other compression approaches because it requires the sender to know the size of the receiver's mempool. And in high bandwidth mode, there is no initial message from the receiver with which to pass this information. Now the sender can always guess based on the contents of his own mempool, but as we have learned, mempools often diverge in practice. Graphene v2.2 will deliver mempool sync, which promises to bring mempools into closer alignment. For this reason, we have decided to delay high bandwidth mode until mempool sync ships later this year.

**Comment by bissias** [comment]
> Many of this feedback was provided for version 1 and hasn't changed much.

> Stepping back, I'm surprised to find a request for comment now while:
1/ No attempt to discuss the spec has been made prior for month now.
2/ Most of the feedback from the previous iteration has not been addressed.

I'm genuinely sorry that you feel this way, and would like to try to change that. While I admit that I've been slow on releasing the latest spec, I have tried to incorporate your feedback specifically. Last year you pointed out that CBloomFilter uses a lot of extra fields and we have come back with a slimmer implementation in CVariableFastFilter. You pointed out that sipHash should be used for cheap hashes, a change that we have made. You also argued that it is impossible to implement graphene without a specification for the IBLT, which I have included with this latest spec. All of these things were excellent suggestions, which is why I'm grateful for your participation. Of course there is always going to be some pushback on certain issues, but overall I hope that you will agree that we're moving in the right direction together.

**Pull request merged**
