### PR TITLE
Remove unnecessary clientversion.h includes

### PR DESCRIPTION
**Pull request by ptschip**

### CODE REVIEW

**Comment by sickpig** [comment]
couldn't we do the same for the same for the `dev` branch?

**Comment by ptschip** [comment]
@sickpig i will when this gets merged.

**Review by marcusdiaz — APPROVED** [review]
All tests passed. Looks good!

**Comment by gandrewstone** [comment]
clientversion.h was needed because that's where the BITCOIN_CASH define was placed.  Its good to clean this up.

**Pull request merged**
