### PR TITLE
FIX: temp band aid to fix issue #84

### PR DESCRIPTION
**Pull request by sickpig**
A more proper fix is to limit orphan tx size like we already do
for normal transaction. Peter Thscipper will take care of it in
a new PR soon.

### CODE REVIEW

**Comment by gandrewstone** [comment]
We will remember this one because it it the first,  but in general, I would like to see a comment on the line saying something like "//BU REVERT this change back to 10 once blah, blah blah

And a comment in the check in or here detailing how and why the band aid fixes things... or whether it just basically NO-OPs the test.

**Comment by sickpig** [comment]
sorry but I didn't thought it would have been merged as is. I opened it more as a reminder rather than anything else. 

That said this band aid fixes make check issue as described in #84. 

Peter think that the test is probably failing because we're running it too many times. So we have limited the test to just one transaction rather than 10 and it worked. Peter is actually working on a proper fix.

**Comment by DanielFragaBR** [comment]
@sickpig I have the same issue ("signal: SIGABRT (application abort requested)") several times. Should I just attach the file here or open a new issue? What do you prefer?

**Comment by sickpig** [comment]
@DanielFragaBR which version of BU are you running? the fix is not contained in the last stable release so if your using BU very 0.12.1c (compiled from source, downloaded from by website or installed from Ubuntu ppa repo) it's normally to experience such issue.

To get it fixed just compile 0.12.1bu branch or install BU via the unstable channel of Ubuntu repo, see: https://launchpad.net/~bitcoin-unlimited/+archive/ubuntu/bu-ppa-nightly

**Comment by DanielFragaBR** [comment]
@sickpig I'm using the most updated git version (f8a1fb7). I tried to use the git version to see if it was fixed. Should it be fixed in the latest git version?

[test-suite.txt](https://github.com/BitcoinUnlimited/BitcoinUnlimited/files/545479/test-suite.txt)

**Comment by sickpig** [comment]
@DanielFragaBR which system are you running (arch + OS)?

**Comment by DanielFragaBR** [comment]
@sickpig Linux 4.8.4 (Linux from scratch). If the issue is with the location of libraries or something related, just ask what you need so I can check.

**Comment by sickpig** [comment]
wow Linux from scratch! I think that this will make things harder to debug from our side. I'll try to setup a virtual machine and give it a try at reproducing the bug.

**Comment by DanielFragaBR** [comment]
I think there's no need to waste your time installing it on a VM.

The error "unknown location(0): fatal error: in "reverselock_tests/reverselock_errors": signal: SIGABRT (application abort requested)
test/reverselock_tests.cpp(51): last checkpoint"

refers exactly to what? I mean, the "unknown location". Is is trying to find what exactly? Maybe it's easier if you could give me a debug command and I execute here... Or if you want I can apply some patch to show this result in a more verbose way, what do you think?

**Comment by sickpig** [comment]
@DanielFragaBR your back trace is slightly different form the one originally posted on issue #84, in fact the first line of the original trace was: 

```
Running 182 test cases...
../../src/test/DoS_tests.cpp(172): error: in "DoS_tests/DoS_mapOrphans": check AddOrphanTx(tx, i) has failed
terminate called without an active exception
```

whereas yours is:

```
Running 187 test cases...
unknown location(0): fatal error: in "reverselock_tests/reverselock_errors": signal: SIGABRT (application abort requested)
test/reverselock_tests.cpp(51): last checkpoint
```

the proper fix by @ptschip was merged already (see #100), mine was just a band aid. 

So I don't know if the test causing the SIGABRT is the same. That said do you have some log file somewhere in the `test/` dir ?

**Comment by DanielFragaBR** [comment]
@sickpig I have just "test_bitcoin.log" (with the same errors from test-suite above).

**Comment by ftrader** [comment]
@DanielFragaBR : I've seen the SIGABRT in reverselock_errors only when I built using very special compiler options.

You didn't do anything special to e.g. add compiler checks beyond what the current build process does?

**Comment by DanielFragaBR** [comment]
I just use the following when configuring:

```
LDFLAGS="-L/usr/local/BerkeleyDB/lib -L/usr/local/ssl/lib" CPPFLAGS="-I/usr/local/BerkeleyDB/include -I/usr/local/ssl/include" ./configure --with-incompatible-bdb
```

It's very strange because it never happened with previous versions (including when I still used Core). I'm also using Boost 1.59. I don't know if there's something specific to this version affecting the tests...

**Pull request merged**
