### PR TITLE
Support freebsd

### PR DESCRIPTION
**Pull request by BlinkyStitt**
Adds docs for building on FreeBSD 9.3 and fixes a deprecated name (https://github.com/BitcoinUnlimited/BitcoinUnlimited/issues/38).

### CODE REVIEW

**Comment by BlinkyStitt** [comment]
Unfortunately, something is still needed because I get a segmentation fault in bitcoind right away. 

At least bitcoin-tx and bitcoin-cli display their help and `bitcoin-cli getinfo` works with my currently running classic node.

```
$ gmake check
Making check in src
gmake[1]: Entering directory '/usr/home/bitcoin/src/BitcoinUnlimited/src'
gmake[2]: Entering directory '/usr/home/bitcoin/src/BitcoinUnlimited/src'
gmake  check-TESTS check-local
gmake[3]: Entering directory '/usr/home/bitcoin/src/BitcoinUnlimited/src'
gmake[4]: Entering directory '/usr/home/bitcoin/src/BitcoinUnlimited/src'
Segmentation fault
FAIL: test/test_bitcoin
============================================================================
Testsuite summary for Bitcoin Unlimited 0.12.1
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See src/test-suite.log
Please report to https://github.com/BitcoinUnlimited/BitcoinUnlimited/issues
============================================================================
gmake[4]: *** [Makefile:7281: test-suite.log] Error 1
gmake[4]: Leaving directory '/usr/home/bitcoin/src/BitcoinUnlimited/src'
gmake[3]: *** [Makefile:7389: check-TESTS] Error 2
gmake[3]: Leaving directory '/usr/home/bitcoin/src/BitcoinUnlimited/src'
gmake[2]: *** [Makefile:7492: check-am] Error 2
gmake[2]: Leaving directory '/usr/home/bitcoin/src/BitcoinUnlimited/src'
gmake[1]: *** [Makefile:7173: check-recursive] Error 1
gmake[1]: Leaving directory '/usr/home/bitcoin/src/BitcoinUnlimited/src'
gmake: *** [Makefile:649: check-recursive] Error 1

```

**Comment by BlinkyStitt** [comment]
FWIW, these same build steps work fine for me with XT and Classic and Core

**Comment by sickpig** [comment]
Hi Bryan, 

thanks for your effort. it is really appreciated!

Could you please apply your PR to https://github.com/ptschip/bitcoin/tree/testall and test again? 

This a branch that @ptschip created to fix the known crashes and potential deadlocks and it should be stable.

thanks 

edit: could you also check `src/test-suite.log` for additional info?

**Comment by BlinkyStitt** [comment]
Testing against @ptschip's branch now and I got this error:

```
Making all in src
gmake[1]: Entering directory '/usr/home/bitcoin/src/BitcoinUnlimited/src'
gmake[2]: Entering directory '/usr/home/bitcoin/src/BitcoinUnlimited/src'
gmake[3]: Entering directory '/usr/home/bitcoin/src/BitcoinUnlimited/src/secp256k1'
gmake[3]: Leaving directory '/usr/home/bitcoin/src/BitcoinUnlimited/src/secp256k1'
  CXX      bitcoind-bitcoind.o
In file included from bitcoind.cpp:16:
./unlimited.h:206:97: error: use of undeclared identifier 'cs_threadblockvalidation'
extern std::map<boost::thread::id, CHandleBlockMsgThreads> mapBlockValidationThreads GUARDED_BY(cs_threadblockvalidation);
                                                                                                ^
./threadsafety.h:18:49: note: expanded from macro 'GUARDED_BY'
#define GUARDED_BY(x) __attribute__((guarded_by(x)))
                                                ^
1 error generated.
gmake[2]: *** [Makefile:6182: bitcoind-bitcoind.o] Error 1
gmake[2]: Leaving directory '/usr/home/bitcoin/src/BitcoinUnlimited/src'
gmake[1]: *** [Makefile:7173: all-recursive] Error 1
gmake[1]: Leaving directory '/usr/home/bitcoin/src/BitcoinUnlimited/src'
gmake: *** [Makefile:649: all-recursive] Error 1
```

**Comment by sickpig** [comment]
I've just cloned @ptschip forked repo and built `testall` branch with this configure options: 

`./configure --without-gui --without-miniupnpc --disable-zmq`

The `make check` complete without errors.

I'm on an ubuntu system (16.04/amd64), so it seems that the `testall` reintroduce some incompatibility with your FreeBSD env (I take for granted that you have already applied this PR on top of the `testall` branch).

I've looked at the code and it seems indeed that `cs_threadblockvalidation` has never declared. 

Dunno why my gcc is not complaining about it.

Could please apply the following on top of the `testall` branch? 

```
diff --git a/src/unlimited.h b/src/unlimited.h
index 5570163..50f7093 100644
--- a/src/unlimited.h
+++ b/src/unlimited.h
@@ -203,6 +203,7 @@ struct CHandleBlockMsgThreads {
     int64_t nStartTime;
     uint64_t nBlockSize;
 };
+extern CCriticalSection cs_threadblockvalidation;
 extern std::map<boost::thread::id, CHandleBlockMsgThreads> mapBlockValidationThreads GUARDED_BY(cs_threadblockvalidation);
 extern CCriticalSection cs_blockvalidationthread;
```

edit: sorry but at the moment I've no access to any FreeBSD machines and even it was the case it'd take quite a bit to get accustomed to the system since I never used it.

**Comment by ptschip** [comment]
thanks for that Andrea...

**Comment by ptschip** [comment]
actually that's a bug, i fixed now in the main branch...

it should be
|
- extern CCriticalSection |||cs_blockvalidationthread|;||
- extern std::map<boost::thread::id, CHandleBlockMsgThreads>
  mapBlockValidationThreads GUARDED_BY(cs_|||blockvalidationthread|); |

||- extern std::map<boost::thread::id, CHandleBlockMsgThreads>
mapBlockValidationThreads GUARDED_BY(cs_threadblockvalidation); |-
extern CCriticalSection cs_blockvalidationthread; |

—

**Comment by sickpig** [comment]
yeah the cs_ variable was declared after it was used for the first time. But the were also a problme ith the variable name. it was declared as `cs_blockvalidationthread` and referred as `cs_threadblockvalidation`.

@WyseNynja could you pull the latest version of `testall` branch and give it a try?

**Comment by BlinkyStitt** [comment]
Still getting a segfault with 4f686805b8dec54ade4b2dbb3f2b7f3ab29a8c61 + the changes in this PR.

The log is very unhelpful:

```
   Bitcoin Unlimited 0.12.1: src/test-suite.log
==================================================

# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test/test_bitcoin
=======================

FAIL test/test_bitcoin (exit status: 139)

```

I didn't have `--disable-zmq` on my configure, but I don't think I have that library installed so it would have been skipped anyways. Testing now with that flag, but I don't expect a change.

EDIT: Nope. Same result with --disable-zmq.

Building with debug symbols now.

**Comment by sickpig** [comment]
@WyseNynja you should have a more detailed log in `src/test-suite.log`, if you still have the file could you please share it's content?

**Comment by ptschip** [comment]
can you run

./src/test/test_bitcoin

by itself after the build has finished.  it should say which test script
failed.

13/10/2016 8:23 PM, Bryan Stitt wrote:

> |FAIL: test/test_bitcoin =======================|

**Comment by gandrewstone** [comment]
also, if you compile with -O0 and -g, then turn on core dumps "ulimit -c unlimited", we might get some more info on what the problem is.  It could be an issue with initialization order of global variables.  We had problems with this in Unlimited, and fixed them by moving variables to unlimited.cpp since compilers can order global variable initialization within a single file.

**Comment by BlinkyStitt** [comment]
The logs of test_bitcoin are essentially empty. Same as I posted earlier. It segfaults very early. 

I'll poke around with gdb now that it's compiled with the debug symbols and see what I can find. I haven't had to deal with segfaults like this since college tho :)

I'm sure it's something in unlimited.cpp since I can compile and run all the other forks of the reference client on this same system

**Comment by BlinkyStitt** [comment]
I did something wrong because the symbols aren't working...

```
[bitcoin@bitcoin ~/src/BitcoinUnlimited]$ gdb src/test/test_bitcoin
GNU gdb 6.1.1 [FreeBSD]
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "amd64-marcel-freebsd"...   
Program received signal SIGSEGV, Segmentation fault.
0x0000000803a27b8a in ?? ()
(gdb) bt
#0  0x0000000803a27b8a in ?? ()
#1  0x00000000010da75a in recvMsgBuf ()
#2  0x00000000010da63e in recvMsgBuf ()
#3  0x00000000010da008 in recvMsgBuf ()
#4  0x00000000010d9e6b in recvMsgBuf ()
#5  0x00000000010d9c2b in recvMsgBuf ()
#6  0x00000000010dd467 in recvMsgBuf ()
#7  0x00000000010bc885 in recvMsgBuf ()
#8  0x00000000016f2f40 in ?? ()
#9  0x0000000002142d00 in ?? ()
#10 0x0000000002142d00 in ?? ()
#11 0x0000000002142d00 in ?? ()
#12 0x0000000002142e70 in ?? ()
#13 0x0000000002142e38 in ?? ()
#14 0x90c697f6642daff7 in ?? ()
#15 0x00007fffffffe9b0 in ?? ()
#16 0x000000000173c3d7 in ?? ()
#17 0x00000000ffffe9a0 in ?? ()
#18 0x0000000804c1a820 in ?? ()
#19 0x000000000213b430 in ?? ()
#20 0x000000000213b410 in ?? ()
#21 0x000000000213b3e0 in ?? ()
---Type <return> to continue, or q <return> to quit---
#22 0x000000000213b3b0 in ?? ()
#23 0x000000000213b3b0 in ?? ()
#24 0x000000000213b3b0 in ?? ()
#25 0x00007fffffffea10 in ?? ()
#26 0x00007fffffffeab8 in ?? ()
#27 0x00007fffffffeaa8 in ?? ()
#28 0x000000080440c512 in ?? ()
#29 0x000000000213b3b0 in ?? ()
#30 0x90c697f6642daff7 in ?? ()
#31 0x00007fffffffea10 in ?? ()
#32 0x00000000016f2e71 in ?? ()
#33 0x0000000802486b30 in ?? ()
#34 0x000000000207e008 in ?? ()
#35 0x000000000213b3b0 in ?? ()
#36 0x00000000016f7f60 in ?? ()
#37 0x00007fffffffea20 in ?? ()
#38 0x00000000016f7f5e in ?? ()
#39 0x00007fffffffea40 in ?? ()
#40 0x0000000001a0e092 in ?? ()
#41 0x0000000000000001 in ?? ()
#42 0x0000000000000001 in ?? ()
#43 0x00007fffffffea80 in ?? ()
---Type <return> to continue, or q <return> to quit---
#44 0x00000000010a3796 in addrman ()
#45 0x0000000000000000 in ?? ()
(gdb) 
```

I'm traveling this weekend, but might have some more time to tinker in airports or on the plane.

**Comment by deadalnix** [comment]
All these long max fixes have been changed, in a way that's actually standard C++ . I believe what remains is the build instructions. If the author wishes to update his PR to use the long max that is not merged, I think this can be safely merged.

**Comment by BlinkyStitt** [comment]
I'm moving my server around and the new one isn't FreeBSD.

However, it looks like someone else opened a different FreeBSD issue: https://github.com/BitcoinUnlimited/BitcoinUnlimited/issues/304

**Pull request closed without merging**
