### PR TITLE
Remove old wallet_ismine.cpp

### LINKED ISSUE #1391: Build Question wallet_ismine.cpp weird include?
At the start of `src/wallet/wallet_ismine.cpp` there's an include to a non-existent file `wallet_ismine.h`

https://github.com/BitcoinUnlimited/BitcoinUnlimited/blob/8081f56d4fc3eb888b1fd0bbf8f3d0fd38dc444b/src/wallet/wallet_ismine.cpp#L7

Is `wallet_ismine.cpp` somehow excluded from the build process? If so how? is it auto-generated with the Makefile based build?

(just trying to understand the build as I'm making a `CMakeLists.txt` for personal use and found this building issue, for now I'm just excluding this file from my build)

### PR DESCRIPTION
**Pull request by awemany**
as it got renamed in this commit:

c477d82a71c624f16f3020174eb3a12bdaab13eb

and then accidentally reintroduced in a merge in this commit:

2b6abf95eff33101309f4ea38e308c5d4cd06804

Closes #1391.

### CODE REVIEW

**Review by sickpig — APPROVED** [review]
Nice catch!

**Comment by awemany** [comment]
> Nice catch!

That goes to @gubatron for finding this.

**Comment by sickpig** [comment]
Thanks @gubatron

**Review by sickpig — CHANGES_REQUESTED** [review]
@awemany you need to remove wallet/wallet_ismine.cpp from .formatted-files

**Comment by gubatron** [comment]
Thank you for acting on it so quickly. Cheers

**Comment by awemany** [comment]
@sickpig: Done.

**Review by Greg-Griffith — APPROVED** [review]

**Review by sickpig — APPROVED** [review]

**Pull request merged**
