### PR TITLE
[Backport] Fix LibreSSL builds

### PR DESCRIPTION
**Pull request by kyuupichan**
This gets a complete build working on DragonflyBSD at least, including Qt.

I've not yet managed to get make check to finish; something entirely unrelated seems to be causing it to get stuck in threading in the tests.  But this at least is a much better state than currently, where it doesn't even build.

This should go on top of #345 

Core PR bitcoin#9475

### CODE REVIEW

**Comment by deadalnix** [comment]
This break for SSL version 1.1 . There must be pieces of the backport which are missing. Please fix or revert.

**Comment by sickpig** [comment]
error while building? do you have the actual error message?

**Comment by deadalnix** [comment]
../../src/qt/paymentrequestplus.cpp: In member function ‘bool PaymentRequestPlus::getMerchant(X509_STORE*, QString&) const’:
    ../../src/qt/paymentrequestplus.cpp:167:20: error: aggregate ‘EVP_MD_CTX _ctx’ has incomplete type and cannot be defined
         EVP_MD_CTX _ctx;

**Comment by kyuupichan** [comment]
Hmm, this part of configure.ac is the same in bitcoin core today

**Comment by deadalnix** [comment]
If this can't be fixed, this needs to be reverted. Broken build is a no no (also I'm trying to get BU packed into debian, so that'd be great if we could ensure the build is green on that distro).

**Comment by kyuupichan** [comment]
This is working on two systems I have access to, and all the buildbot systems. Only you have access to yours. 

It would be helpful if you could point out why it is behaving differently on yours, and whether Core, which also has this patch, fails for you in the same way.

**Comment by deadalnix** [comment]
No core builds just fine. I mentioned the error message and also mentioned the cause, OpenSSL 1.1 . Not building with OpenSSL 1.1 is not an option anyway, it is the default for more and more distros. If you want to repro, try to build with that.

**Comment by deadalnix** [comment]
Looks like the trunk is back to green. Was this reverted ? I don't see this in history. Either way, we are good.

**Comment by kyuupichan** [comment]
Huh? So what changed?

**Comment by deadalnix** [comment]
I have no idea, looking at the history nothing obvious. Maybe it isn't on our side, but on debian's ?

**Pull request merged**
