### PR TITLE
Avoid using floating point arithmetic to compute EB

### PR DESCRIPTION
**Pull request by sickpig**

### CODE REVIEW

**Comment by awemany** [comment]
Concept ACK, but should include tests from ABC as well.

**Comment by sickpig** [comment]
putting it on WIP, need to add more tests and simplify the code a little.

**Comment by sickpig** [comment]
@gandrewstone  ready to be reviewed

**Comment by sickpig** [comment]
looking at travis failure now

**Comment by sickpig** [comment]
closing, need to find out what's wrong

**Pull request closed without merging**
