### PR TITLE
Do not re-request a block if it is currently being processed

### PR DESCRIPTION
**Pull request by ptschip**
Solves the performance issue where a large and long to validate block would end up being re-requested multiple times by the request manager.

### CODE REVIEW

**Comment by sickpig** [comment]
utACK. code sounds good.

will test locally and report back.

**Comment by ptschip** [comment]
@sickpig any test results

> utACK. code sounds good.
> 
> will test locally and report back.

**Review by sickpig — APPROVED** [review]
test extensively. no problem at all.

**Comment by gandrewstone** [comment]
Note that this PR is not a comprehensive solution.  We also need to identify when a block is in the process of being downloaded, and monitor that it continues to be downloaded at a reasonable bandwith.  If those conditions are met, we can use the same fProcessing flag defined here to defer re-requests.  Due to the way the network layer is designed (messages are held within the layer until completely downloaded), implementing the above is going to be awkward.  We will have to implement some sort of "peek" API that allows higher layers to look at incomplete incoming messages.  

And a complete implementation would use block property commitments so that block sizes are safely advertised to other nodes in INVs

**Comment by msdavid89** [comment]
I think that if an attacker creates a block with a timestamp too far in the future and performs an unsolicited block push, nodes will set fProcessing to true and then never re-request the block when they actually need it, should that block be accepted into the consensus branch in the future. I haven't fully traced through the code to see if this could present real problems, but you can at least fix what I am seeing pretty easily: in ProcessMessage(), for BLOCK messages, there is a call to CheckBlockHeader() which would catch this, but currently only prevents you from sending over expedited. If that check fails, then don't enter HandleBlockMessage().

**Comment by ptschip** [comment]
If for instance they force pushed us a block, then it wouldn't be in the
request manager yet and so we wouldn't/couldn't set the flag to
processing...and if we had already received the block announcement from
some other peer then we would most likely already have requested it by
the time we got an unrequested full block so  I dont' think the risk is
all that high as it would be a pretty hard to pull off event, but still
I think I'll tidy up the code there and fix that...

**Comment by ptschip** [comment]
fixed in #1776.  If the block fails  AcceptBlock() we reset the
fProcessing flag to false.

**Pull request merged**
