### PR TITLE
Doxygen

### PR DESCRIPTION
**Pull request by soeren-b-c**
Make configure.ac update the Doxyfile version, and cleanup some text, logo etc.

See http://173.212.248.165/BU-dev/ for doxygen output.

### CODE REVIEW

**Review by sickpig — COMMENTED** [review]
travis is complaining about format of a bunch of comments in bitcoin.cpp

https://travis-ci.org/BitcoinUnlimited/BitcoinUnlimited/jobs/478291495#L786

**Comment by soeren-b-c** [comment]
@sickpig Thanks for your feedback. I think I have fixed the formatting now (do correct me if I'm wrong), but I don't know what to do about the current check fails.
Could you point me in the right direction?

**Comment by sickpig** [comment]
@soeren-b-c Travis timed out, not your fault. Restarted failing travis jobs now everything is ok.

**Comment by gandrewstone** [comment]
its great to have doxygen documentation! Thanks

**Pull request merged**
