### PR TITLE
Fix walletbackup.py failure in Python 3.5+

### PR DESCRIPTION
**Pull request by dgenr8**
This fixes two RPC tests for me, and eliminates some spurious output while running the test suite.

### CODE REVIEW

**Comment by gandrewstone** [comment]
I'm happy to merge to track core if we realize that they are equivalent, but for my understanding why does this work but the original fix in BU not work?  From a quick glance it looks like the BU fix just catches and retries 1 frame above this fix...

**Comment by ftrader** [comment]
I've not had a look at what the exact changes in http.client were, but the revised fix does move this exception handling down from the AuthServiceProxyWrapper to the lower layer (AuthServiceProxy) which is where it is better handled.

I think the handler should be extended for robustness with the ConnectionResetError as per https://github.com/bitcoin/bitcoin/pull/8834#issuecomment-250450213 , i.e.

`except (BrokenPipeError,ConnectionResetError):`

**Comment by gandrewstone** [comment]
@ftrader yes it makes sense to add ConnectionResetError.  

And I agree the exception is better handled at the lower level.  But I fear that we are missing something because how could the exact handling position affect walletbackup.py?

**Comment by dgenr8** [comment]
I didn't look deeply into this.  I tried the core fix and it corrected the test problems mentioned, then I removed the BU fix and no test problems appeared/reappeared.

**Comment by ftrader** [comment]
walletbackup.py passes for me with Python 3.5.2 on unpatched `dev` (9a99acdadc226e6a116f326fd8fa64c9cdbcad6b), but with strange output during test which indicates that something is tripped:

```
...
Connection broken:  [Errno 32] Broken pipe
[214, 214, 214, 214]
Stopping nodes
Cannot send request: Request-sent
...
```

**Comment by gandrewstone** [comment]
Ok since its better to handle the error lower in the stack, I will merge this.

**Pull request merged**
