### PR TITLE
DbEnv constructor param explicit cast to avoid compilation error in macOS

### PR DESCRIPTION
**Pull request by gubatron**
(I apologize for the re-submission, I removed my repo's branch by mistake and the PR auto-closed on BitcoinUnlimited's PR queue.)

### CODE REVIEW

**Comment by ptschip** [comment]
no worries, everybody does that from time to time :)

**Comment by Greg-Griffith** [comment]
@gubatron is this a compiler error or just a warning?

**Comment by gubatron** [comment]
Compiler error for me.
screen shot 2018-10-10 at 9 00 24 pm

**Comment by gubatron** [comment]
This is my compiler
```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.10.44.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by Greg-Griffith** [comment]
@gubatron that's very interesting...  
my only nit about this is the type u_int32_t. Please try to stick to the int types defined in [stdint](http://www.cplusplus.com/reference/cstdint/) so that they are universally portable. It just makes things easier

**Review by ptschip — APPROVED** [review]
sorry this took so long...

**Comment by gubatron** [comment]
Thank you!

**Pull request merged**
